-- Restore seed data lost during database reset

UPDATE public.products SET category_slug = NULL, category_name = NULL, subcategory_slug = NULL, subcategory_name = NULL;
DELETE FROM public.categories;

INSERT INTO public.categories (name, slug, icon, parent_id, sort_order) VALUES
  ('Women''s Fashion',            'womens-fashion',           '👗', NULL, 1),
  ('Men''s Fashion',              'mens-fashion',             '👔', NULL, 2),
  ('Watches, Bags & Jewellery',   'watches-bags-jewellery',   '⌚', NULL, 3),
  ('Mother & Baby',               'mother-baby',              '🍼', NULL, 4),
  ('Home & Lifestyle',            'home-lifestyle',           '🏠', NULL, 5),
  ('Electronic Devices',          'electronic-devices',       '💻', NULL, 6),
  ('TV & Home Appliances',        'tv-home-appliances',       '📺', NULL, 7),
  ('Electronic Accessories',      'electronic-accessories',   '🎧', NULL, 8),
  ('Health & Beauty',             'health-beauty',            '💄', NULL, 9),
  ('Groceries & Pets',            'groceries-pets',           '🛒', NULL, 10),
  ('Sports & Outdoor',            'sports-outdoor',           '⚽', NULL, 11),
  ('Automotive & Motorbike',      'automotive-motorbike',     '🚗', NULL, 12);

WITH subs(parent_slug, name, slug, sort_order) AS (
  VALUES
    ('womens-fashion','Muslim Wear','womens-fashion-muslim-wear',1),
    ('womens-fashion','Sarees','womens-fashion-sarees',2),
    ('womens-fashion','Salwar Kameez','womens-fashion-salwar-kameez',3),
    ('womens-fashion','Kurtis & Tunics','womens-fashion-kurtis-tunics',4),
    ('womens-fashion','Tops','womens-fashion-tops',5),
    ('womens-fashion','Dresses','womens-fashion-dresses',6),
    ('womens-fashion','Traditional Wear','womens-fashion-traditional',7),
    ('womens-fashion','Winter Clothing','womens-fashion-winter',8),
    ('womens-fashion','Lingerie & Sleepwear','womens-fashion-lingerie',9),
    ('womens-fashion','Shoes','womens-fashion-shoes',10),
    ('womens-fashion','Sandals','womens-fashion-sandals',11),
    ('womens-fashion','Sportswear','womens-fashion-sportswear',12),
    ('womens-fashion','Accessories','womens-fashion-accessories',13),
    ('mens-fashion','T-Shirts','mens-fashion-tshirts',1),
    ('mens-fashion','Polo Shirts','mens-fashion-polo',2),
    ('mens-fashion','Shirts','mens-fashion-shirts',3),
    ('mens-fashion','Panjabi & Fatua','mens-fashion-panjabi',4),
    ('mens-fashion','Pants','mens-fashion-pants',5),
    ('mens-fashion','Jeans','mens-fashion-jeans',6),
    ('mens-fashion','Shorts','mens-fashion-shorts',7),
    ('mens-fashion','Traditional Wear','mens-fashion-traditional',8),
    ('mens-fashion','Winter Clothing','mens-fashion-winter',9),
    ('mens-fashion','Innerwear & Sleepwear','mens-fashion-innerwear',10),
    ('mens-fashion','Formal Shoes','mens-fashion-formal-shoes',11),
    ('mens-fashion','Sneakers','mens-fashion-sneakers',12),
    ('mens-fashion','Sandals & Flip-Flops','mens-fashion-sandals',13),
    ('mens-fashion','Sportswear','mens-fashion-sportswear',14),
    ('mens-fashion','Accessories','mens-fashion-accessories',15),
    ('watches-bags-jewellery','Men''s Watches','wbj-mens-watches',1),
    ('watches-bags-jewellery','Women''s Watches','wbj-womens-watches',2),
    ('watches-bags-jewellery','Kids Watches','wbj-kids-watches',3),
    ('watches-bags-jewellery','Sunglasses & Eyewear','wbj-eyewear',4),
    ('watches-bags-jewellery','Women''s Bags','wbj-womens-bags',5),
    ('watches-bags-jewellery','Men''s Bags','wbj-mens-bags',6),
    ('watches-bags-jewellery','Backpacks','wbj-backpacks',7),
    ('watches-bags-jewellery','Luggage','wbj-luggage',8),
    ('watches-bags-jewellery','Fashion Jewellery','wbj-fashion-jewellery',9),
    ('watches-bags-jewellery','Fine Jewellery','wbj-fine-jewellery',10),
    ('watches-bags-jewellery','Wallets','wbj-wallets',11),
    ('mother-baby','Diapers & Potty','mb-diapers',1),
    ('mother-baby','Baby Feeding','mb-feeding',2),
    ('mother-baby','Milk Formula','mb-milk-formula',3),
    ('mother-baby','Baby & Toddler Food','mb-toddler-food',4),
    ('mother-baby','Baby Personal Care','mb-baby-care',5),
    ('mother-baby','Baby Clothing','mb-baby-clothing',6),
    ('mother-baby','Baby Gear','mb-gear',7),
    ('mother-baby','Nursery','mb-nursery',8),
    ('mother-baby','Maternity Care','mb-maternity',9),
    ('mother-baby','Toys & Games','mb-toys-games',10),
    ('mother-baby','Educational Toys','mb-educational-toys',11),
    ('home-lifestyle','Bedding & Bath','home-bedding-bath',1),
    ('home-lifestyle','Home Decor','home-decor',2),
    ('home-lifestyle','Kitchenware','home-kitchenware',3),
    ('home-lifestyle','Cookware','home-cookware',4),
    ('home-lifestyle','Dining & Serveware','home-dining',5),
    ('home-lifestyle','Furniture','home-furniture',6),
    ('home-lifestyle','Lighting','home-lighting',7),
    ('home-lifestyle','Tools & DIY','home-tools-diy',8),
    ('home-lifestyle','Laundry & Cleaning','home-laundry-cleaning',9),
    ('home-lifestyle','Storage & Organization','home-storage',10),
    ('home-lifestyle','Stationery & Crafts','home-stationery',11),
    ('home-lifestyle','Books','home-books',12),
    ('home-lifestyle','Party Supplies','home-party',13),
    ('electronic-devices','Mobiles','ed-mobiles',1),
    ('electronic-devices','Tablets','ed-tablets',2),
    ('electronic-devices','Laptops','ed-laptops',3),
    ('electronic-devices','Desktops','ed-desktops',4),
    ('electronic-devices','Gaming Consoles','ed-gaming-consoles',5),
    ('electronic-devices','DSLR & Mirrorless Cameras','ed-dslr',6),
    ('electronic-devices','Point & Shoot Cameras','ed-cameras',7),
    ('electronic-devices','Action Cameras','ed-action-cams',8),
    ('electronic-devices','Drones','ed-drones',9),
    ('electronic-devices','Wearable Tech','ed-wearable',10),
    ('electronic-devices','Smart Watches','ed-smartwatch',11),
    ('tv-home-appliances','Televisions','tvha-tvs',1),
    ('tv-home-appliances','Home Audio','tvha-home-audio',2),
    ('tv-home-appliances','Projectors','tvha-projectors',3),
    ('tv-home-appliances','Air Conditioners','tvha-ac',4),
    ('tv-home-appliances','Refrigerators','tvha-fridge',5),
    ('tv-home-appliances','Freezers','tvha-freezer',6),
    ('tv-home-appliances','Washing Machines','tvha-washing',7),
    ('tv-home-appliances','Kitchen Appliances','tvha-kitchen-app',8),
    ('tv-home-appliances','Microwaves & Ovens','tvha-microwaves',9),
    ('tv-home-appliances','Water Purifiers','tvha-water-purifiers',10),
    ('tv-home-appliances','Vacuum Cleaners','tvha-vacuum',11),
    ('tv-home-appliances','Fans','tvha-fans',12),
    ('tv-home-appliances','Irons','tvha-irons',13),
    ('tv-home-appliances','Personal Care Appliances','tvha-personal',14),
    ('electronic-accessories','Mobile Accessories','ea-mobile-acc',1),
    ('electronic-accessories','Phone Cases','ea-phone-cases',2),
    ('electronic-accessories','Screen Protectors','ea-screen-prot',3),
    ('electronic-accessories','Chargers & Cables','ea-chargers',4),
    ('electronic-accessories','Power Banks','ea-power-banks',5),
    ('electronic-accessories','Headphones & Earbuds','ea-headphones',6),
    ('electronic-accessories','Bluetooth Speakers','ea-bt-speakers',7),
    ('electronic-accessories','Wearable Accessories','ea-wearable-acc',8),
    ('electronic-accessories','Camera Accessories','ea-camera-acc',9),
    ('electronic-accessories','Storage & Memory','ea-storage',10),
    ('electronic-accessories','Computer Accessories','ea-computer-acc',11),
    ('electronic-accessories','Printers & Ink','ea-printers',12),
    ('electronic-accessories','Networking Devices','ea-networking',13),
    ('electronic-accessories','Gaming Accessories','ea-gaming-acc',14),
    ('health-beauty','Skin Care','hb-skincare',1),
    ('health-beauty','Hair Care','hb-haircare',2),
    ('health-beauty','Makeup','hb-makeup',3),
    ('health-beauty','Fragrances','hb-fragrances',4),
    ('health-beauty','Bath & Body','hb-bath-body',5),
    ('health-beauty','Men''s Grooming','hb-mens-grooming',6),
    ('health-beauty','Beauty Tools','hb-beauty-tools',7),
    ('health-beauty','Personal Care','hb-personal-care',8),
    ('health-beauty','Health Supplements','hb-supplements',9),
    ('health-beauty','Medical Supplies','hb-medical',10),
    ('health-beauty','Sexual Wellness','hb-sexual-wellness',11),
    ('health-beauty','Oral Care','hb-oral-care',12),
    ('groceries-pets','Rice, Pasta & Noodles','gp-rice-pasta',1),
    ('groceries-pets','Cooking Essentials','gp-cooking',2),
    ('groceries-pets','Snacks','gp-snacks',3),
    ('groceries-pets','Beverages','gp-beverages',4),
    ('groceries-pets','Breakfast Foods','gp-breakfast',5),
    ('groceries-pets','Dairy & Chilled','gp-dairy',6),
    ('groceries-pets','Frozen Foods','gp-frozen',7),
    ('groceries-pets','Baking Needs','gp-baking',8),
    ('groceries-pets','Canned & Jarred','gp-canned',9),
    ('groceries-pets','Dog Food & Supplies','gp-dog-supplies',10),
    ('groceries-pets','Cat Food & Supplies','gp-cat-supplies',11),
    ('groceries-pets','Fish & Aquatics','gp-fish-aquatics',12),
    ('groceries-pets','Bird Supplies','gp-bird-supplies',13),
    ('sports-outdoor','Exercise & Fitness','so-fitness',1),
    ('sports-outdoor','Cycling','so-cycling',2),
    ('sports-outdoor','Team Sports','so-team-sports',3),
    ('sports-outdoor','Cricket','so-cricket',4),
    ('sports-outdoor','Football','so-football',5),
    ('sports-outdoor','Badminton','so-badminton',6),
    ('sports-outdoor','Racket Sports','so-racket',7),
    ('sports-outdoor','Water Sports','so-water-sports',8),
    ('sports-outdoor','Camping & Hiking','so-camping',9),
    ('sports-outdoor','Fishing','so-fishing',10),
    ('sports-outdoor','Sports Shoes','so-shoes',11),
    ('sports-outdoor','Sports Apparel','so-apparel',12),
    ('sports-outdoor','Sports Accessories','so-accessories',13),
    ('automotive-motorbike','Automotive Tools','am-tools',1),
    ('automotive-motorbike','Car Care','am-car-care',2),
    ('automotive-motorbike','Car Electronics','am-car-electronics',3),
    ('automotive-motorbike','Interior Accessories','am-interior',4),
    ('automotive-motorbike','Exterior Accessories','am-exterior',5),
    ('automotive-motorbike','Car Safety','am-car-safety',6),
    ('automotive-motorbike','Auto Oils & Fluids','am-oils',7),
    ('automotive-motorbike','Auto Parts & Spares','am-parts',8),
    ('automotive-motorbike','Motorbike Helmets','am-helmets',9),
    ('automotive-motorbike','Motorbike Riding Gear','am-riding-gear',10),
    ('automotive-motorbike','Motorbike Accessories','am-moto-acc',11),
    ('automotive-motorbike','Motorbike Parts','am-moto-parts',12),
    ('automotive-motorbike','Motorbike Tyres','am-moto-tyres',13)
)
INSERT INTO public.categories (name, slug, parent_id, sort_order)
SELECT s.name, s.slug, p.id, s.sort_order
FROM subs s
JOIN public.categories p ON p.slug = s.parent_slug;

WITH l3(parent_slug, name, slug, sort_order) AS (
  VALUES
    ('womens-fashion-sarees','Silk Sarees','wf-sarees-silk',1),
    ('womens-fashion-sarees','Cotton Sarees','wf-sarees-cotton',2),
    ('womens-fashion-sarees','Jamdani','wf-sarees-jamdani',3),
    ('womens-fashion-sarees','Half Silk','wf-sarees-half-silk',4),
    ('womens-fashion-sarees','Georgette','wf-sarees-georgette',5),
    ('womens-fashion-sarees','Party Sarees','wf-sarees-party',6),
    ('womens-fashion-sarees','Wedding Sarees','wf-sarees-wedding',7),
    ('womens-fashion-salwar-kameez','Unstitched','wf-sk-unstitched',1),
    ('womens-fashion-salwar-kameez','Stitched','wf-sk-stitched',2),
    ('womens-fashion-salwar-kameez','Pakistani','wf-sk-pakistani',3),
    ('womens-fashion-salwar-kameez','Indian','wf-sk-indian',4),
    ('womens-fashion-salwar-kameez','Party Wear','wf-sk-party',5),
    ('womens-fashion-muslim-wear','Abayas','wf-mw-abayas',1),
    ('womens-fashion-muslim-wear','Burqas','wf-mw-burqas',2),
    ('womens-fashion-muslim-wear','Hijabs','wf-mw-hijabs',3),
    ('womens-fashion-muslim-wear','Prayer Dresses','wf-mw-prayer',4),
    ('womens-fashion-tops','T-Shirts','wf-tops-tshirts',1),
    ('womens-fashion-tops','Blouses','wf-tops-blouses',2),
    ('womens-fashion-tops','Tank Tops','wf-tops-tanks',3),
    ('womens-fashion-tops','Fatuas','wf-tops-fatuas',4),
    ('womens-fashion-shoes','Heels','wf-shoes-heels',1),
    ('womens-fashion-shoes','Flats','wf-shoes-flats',2),
    ('womens-fashion-shoes','Boots','wf-shoes-boots',3),
    ('womens-fashion-shoes','Sneakers','wf-shoes-sneakers',4),
    ('womens-fashion-shoes','Loafers','wf-shoes-loafers',5),
    ('mens-fashion-tshirts','Half Sleeve','mf-tshirts-half',1),
    ('mens-fashion-tshirts','Full Sleeve','mf-tshirts-full',2),
    ('mens-fashion-tshirts','Graphic Tees','mf-tshirts-graphic',3),
    ('mens-fashion-tshirts','Plain Tees','mf-tshirts-plain',4),
    ('mens-fashion-shirts','Formal Shirts','mf-shirts-formal',1),
    ('mens-fashion-shirts','Casual Shirts','mf-shirts-casual',2),
    ('mens-fashion-shirts','Denim Shirts','mf-shirts-denim',3),
    ('mens-fashion-shirts','Printed Shirts','mf-shirts-printed',4),
    ('mens-fashion-panjabi','Cotton Panjabi','mf-panjabi-cotton',1),
    ('mens-fashion-panjabi','Silk Panjabi','mf-panjabi-silk',2),
    ('mens-fashion-panjabi','Eid Panjabi','mf-panjabi-eid',3),
    ('mens-fashion-panjabi','Kabli','mf-panjabi-kabli',4),
    ('mens-fashion-pants','Formal Pants','mf-pants-formal',1),
    ('mens-fashion-pants','Chinos','mf-pants-chinos',2),
    ('mens-fashion-pants','Cargo Pants','mf-pants-cargo',3),
    ('mens-fashion-pants','Joggers','mf-pants-joggers',4),
    ('mens-fashion-jeans','Slim Fit','mf-jeans-slim',1),
    ('mens-fashion-jeans','Regular Fit','mf-jeans-regular',2),
    ('mens-fashion-jeans','Skinny','mf-jeans-skinny',3),
    ('mens-fashion-jeans','Straight','mf-jeans-straight',4),
    ('mens-fashion-formal-shoes','Oxfords','mf-fs-oxfords',1),
    ('mens-fashion-formal-shoes','Loafers','mf-fs-loafers',2),
    ('mens-fashion-formal-shoes','Derby','mf-fs-derby',3),
    ('mens-fashion-sneakers','Running','mf-sneakers-running',1),
    ('mens-fashion-sneakers','Casual','mf-sneakers-casual',2),
    ('mens-fashion-sneakers','High Tops','mf-sneakers-hightop',3),
    ('ed-mobiles','Samsung','ed-mobiles-samsung',1),
    ('ed-mobiles','Xiaomi','ed-mobiles-xiaomi',2),
    ('ed-mobiles','Realme','ed-mobiles-realme',3),
    ('ed-mobiles','Oppo','ed-mobiles-oppo',4),
    ('ed-mobiles','Vivo','ed-mobiles-vivo',5),
    ('ed-mobiles','Apple iPhone','ed-mobiles-iphone',6),
    ('ed-mobiles','Infinix','ed-mobiles-infinix',7),
    ('ed-mobiles','Tecno','ed-mobiles-tecno',8),
    ('ed-mobiles','Nokia','ed-mobiles-nokia',9),
    ('ed-mobiles','Walton','ed-mobiles-walton',10),
    ('ed-mobiles','Symphony','ed-mobiles-symphony',11),
    ('ed-tablets','Samsung Tablets','ed-tablets-samsung',1),
    ('ed-tablets','Apple iPad','ed-tablets-ipad',2),
    ('ed-tablets','Lenovo Tablets','ed-tablets-lenovo',3),
    ('ed-tablets','Xiaomi Tablets','ed-tablets-xiaomi',4),
    ('ed-tablets','Huawei Tablets','ed-tablets-huawei',5),
    ('ed-laptops','HP','ed-laptops-hp',1),
    ('ed-laptops','Dell','ed-laptops-dell',2),
    ('ed-laptops','Lenovo','ed-laptops-lenovo',3),
    ('ed-laptops','Asus','ed-laptops-asus',4),
    ('ed-laptops','Acer','ed-laptops-acer',5),
    ('ed-laptops','Apple MacBook','ed-laptops-macbook',6),
    ('ed-laptops','MSI','ed-laptops-msi',7),
    ('ed-laptops','Walton Laptops','ed-laptops-walton',8),
    ('ed-laptops','Gaming Laptops','ed-laptops-gaming',9),
    ('ed-smartwatch','Apple Watch','ed-sw-apple',1),
    ('ed-smartwatch','Samsung Galaxy Watch','ed-sw-samsung',2),
    ('ed-smartwatch','Xiaomi Mi Band','ed-sw-xiaomi',3),
    ('ed-smartwatch','Amazfit','ed-sw-amazfit',4),
    ('ed-smartwatch','Fitness Trackers','ed-sw-fitness',5),
    ('ea-headphones','Wireless Earbuds','ea-hp-wireless-earbuds',1),
    ('ea-headphones','Wired Earphones','ea-hp-wired',2),
    ('ea-headphones','Over-Ear Headphones','ea-hp-overear',3),
    ('ea-headphones','Gaming Headsets','ea-hp-gaming',4),
    ('ea-headphones','Neckband Earphones','ea-hp-neckband',5),
    ('ea-headphones','Bluetooth Headsets','ea-hp-bt-headset',6),
    ('ea-power-banks','10000 mAh','ea-pb-10000',1),
    ('ea-power-banks','20000 mAh','ea-pb-20000',2),
    ('ea-power-banks','Fast Charging Power Banks','ea-pb-fast',3),
    ('ea-power-banks','Solar Power Banks','ea-pb-solar',4),
    ('ea-chargers','Fast Chargers','ea-chargers-fast',1),
    ('ea-chargers','Wireless Chargers','ea-chargers-wireless',2),
    ('ea-chargers','USB-C Cables','ea-chargers-usbc',3),
    ('ea-chargers','Lightning Cables','ea-chargers-lightning',4),
    ('ea-chargers','Micro USB Cables','ea-chargers-micro',5),
    ('tvha-tvs','Smart TVs','tvha-tvs-smart',1),
    ('tvha-tvs','4K UHD TVs','tvha-tvs-4k',2),
    ('tvha-tvs','LED TVs','tvha-tvs-led',3),
    ('tvha-tvs','32 Inch','tvha-tvs-32',4),
    ('tvha-tvs','43 Inch','tvha-tvs-43',5),
    ('tvha-tvs','55 Inch','tvha-tvs-55',6),
    ('tvha-tvs','65 Inch','tvha-tvs-65',7),
    ('tvha-ac','Split AC','tvha-ac-split',1),
    ('tvha-ac','Inverter AC','tvha-ac-inverter',2),
    ('tvha-ac','1 Ton','tvha-ac-1ton',3),
    ('tvha-ac','1.5 Ton','tvha-ac-1-5ton',4),
    ('tvha-ac','2 Ton','tvha-ac-2ton',5),
    ('tvha-fridge','Double Door','tvha-fridge-double',1),
    ('tvha-fridge','Single Door','tvha-fridge-single',2),
    ('tvha-fridge','Side By Side','tvha-fridge-sbs',3),
    ('tvha-fridge','Mini Fridge','tvha-fridge-mini',4),
    ('tvha-fans','Ceiling Fans','tvha-fans-ceiling',1),
    ('tvha-fans','Table Fans','tvha-fans-table',2),
    ('tvha-fans','Pedestal Fans','tvha-fans-pedestal',3),
    ('tvha-fans','Rechargeable Fans','tvha-fans-rechargeable',4),
    ('tvha-fans','Exhaust Fans','tvha-fans-exhaust',5),
    ('hb-skincare','Face Wash','hb-skin-facewash',1),
    ('hb-skincare','Moisturizers','hb-skin-moisturizer',2),
    ('hb-skincare','Sunscreen','hb-skin-sunscreen',3),
    ('hb-skincare','Face Serums','hb-skin-serum',4),
    ('hb-skincare','Face Masks','hb-skin-mask',5),
    ('hb-skincare','Toners','hb-skin-toner',6),
    ('hb-skincare','Acne Treatment','hb-skin-acne',7),
    ('hb-makeup','Lipstick','hb-mk-lipstick',1),
    ('hb-makeup','Foundation','hb-mk-foundation',2),
    ('hb-makeup','Eyeliner','hb-mk-eyeliner',3),
    ('hb-makeup','Mascara','hb-mk-mascara',4),
    ('hb-makeup','Eyeshadow','hb-mk-eyeshadow',5),
    ('hb-makeup','Blush','hb-mk-blush',6),
    ('hb-makeup','Nail Polish','hb-mk-nailpolish',7),
    ('hb-haircare','Shampoo','hb-hair-shampoo',1),
    ('hb-haircare','Conditioner','hb-hair-conditioner',2),
    ('hb-haircare','Hair Oil','hb-hair-oil',3),
    ('hb-haircare','Hair Mask','hb-hair-mask',4),
    ('hb-haircare','Hair Color','hb-hair-color',5),
    ('home-furniture','Sofas','home-furn-sofa',1),
    ('home-furniture','Beds','home-furn-bed',2),
    ('home-furniture','Dining Tables','home-furn-dining',3),
    ('home-furniture','Wardrobes','home-furn-wardrobe',4),
    ('home-furniture','Office Chairs','home-furn-office-chair',5),
    ('home-furniture','Study Tables','home-furn-study',6),
    ('home-furniture','Shoe Racks','home-furn-shoerack',7),
    ('home-kitchenware','Pressure Cookers','home-kw-pressure',1),
    ('home-kitchenware','Rice Cookers','home-kw-rice',2),
    ('home-kitchenware','Non-Stick Pans','home-kw-nonstick',3),
    ('home-kitchenware','Knives','home-kw-knives',4),
    ('home-kitchenware','Water Bottles','home-kw-bottles',5),
    ('home-kitchenware','Lunch Boxes','home-kw-lunchbox',6),
    ('gp-beverages','Tea','gp-bev-tea',1),
    ('gp-beverages','Coffee','gp-bev-coffee',2),
    ('gp-beverages','Soft Drinks','gp-bev-softdrinks',3),
    ('gp-beverages','Juices','gp-bev-juices',4),
    ('gp-beverages','Energy Drinks','gp-bev-energy',5),
    ('gp-beverages','Water','gp-bev-water',6),
    ('gp-snacks','Chips & Crisps','gp-snacks-chips',1),
    ('gp-snacks','Biscuits & Cookies','gp-snacks-biscuits',2),
    ('gp-snacks','Chocolates','gp-snacks-chocolate',3),
    ('gp-snacks','Nuts & Dry Fruits','gp-snacks-nuts',4),
    ('gp-snacks','Instant Noodles','gp-snacks-noodles',5),
    ('gp-cooking','Cooking Oil','gp-cook-oil',1),
    ('gp-cooking','Spices','gp-cook-spices',2),
    ('gp-cooking','Salt & Sugar','gp-cook-salt-sugar',3),
    ('gp-cooking','Sauces & Condiments','gp-cook-sauces',4),
    ('gp-cooking','Ghee & Butter','gp-cook-ghee',5),
    ('so-cricket','Cricket Bats','so-cricket-bat',1),
    ('so-cricket','Cricket Balls','so-cricket-ball',2),
    ('so-cricket','Cricket Gloves','so-cricket-gloves',3),
    ('so-cricket','Cricket Pads','so-cricket-pads',4),
    ('so-cricket','Cricket Helmets','so-cricket-helmet',5),
    ('so-football','Footballs','so-football-ball',1),
    ('so-football','Football Boots','so-football-boots',2),
    ('so-football','Football Jerseys','so-football-jersey',3),
    ('so-football','Shin Guards','so-football-shin',4),
    ('so-fitness','Dumbbells','so-fit-dumbbells',1),
    ('so-fitness','Yoga Mats','so-fit-yoga',2),
    ('so-fitness','Treadmills','so-fit-treadmill',3),
    ('so-fitness','Resistance Bands','so-fit-bands',4),
    ('so-fitness','Skipping Ropes','so-fit-skipping',5),
    ('mb-diapers','Newborn Diapers','mb-diapers-newborn',1),
    ('mb-diapers','Small Diapers','mb-diapers-small',2),
    ('mb-diapers','Medium Diapers','mb-diapers-medium',3),
    ('mb-diapers','Large Diapers','mb-diapers-large',4),
    ('mb-diapers','Pants Style Diapers','mb-diapers-pants',5),
    ('mb-baby-clothing','Baby Boy Clothing','mb-clothing-boy',1),
    ('mb-baby-clothing','Baby Girl Clothing','mb-clothing-girl',2),
    ('mb-baby-clothing','Newborn Sets','mb-clothing-newborn',3),
    ('mb-baby-clothing','Baby Winter Wear','mb-clothing-winter',4),
    ('mb-toys-games','Educational Toys','mb-toys-educational',1),
    ('mb-toys-games','Remote Control Toys','mb-toys-rc',2),
    ('mb-toys-games','Dolls & Plush','mb-toys-dolls',3),
    ('mb-toys-games','Building Blocks','mb-toys-blocks',4),
    ('mb-toys-games','Puzzles','mb-toys-puzzles',5),
    ('mb-toys-games','Outdoor Toys','mb-toys-outdoor',6),
    ('am-helmets','Full Face Helmets','am-helmet-fullface',1),
    ('am-helmets','Half Helmets','am-helmet-half',2),
    ('am-helmets','Modular Helmets','am-helmet-modular',3),
    ('am-helmets','Kids Helmets','am-helmet-kids',4),
    ('am-moto-parts','Engine Parts','am-moto-parts-engine',1),
    ('am-moto-parts','Chain & Sprocket','am-moto-parts-chain',2),
    ('am-moto-parts','Brake Parts','am-moto-parts-brake',3),
    ('am-moto-parts','Lights & Indicators','am-moto-parts-lights',4),
    ('am-moto-parts','Mirrors','am-moto-parts-mirrors',5),
    ('wbj-mens-watches','Analog','wbj-mw-analog',1),
    ('wbj-mens-watches','Digital','wbj-mw-digital',2),
    ('wbj-mens-watches','Chronograph','wbj-mw-chrono',3),
    ('wbj-mens-watches','Leather Strap','wbj-mw-leather',4),
    ('wbj-mens-watches','Steel Strap','wbj-mw-steel',5),
    ('wbj-womens-watches','Analog','wbj-ww-analog',1),
    ('wbj-womens-watches','Digital','wbj-ww-digital',2),
    ('wbj-womens-watches','Bracelet Watches','wbj-ww-bracelet',3),
    ('wbj-womens-bags','Handbags','wbj-wb-handbags',1),
    ('wbj-womens-bags','Shoulder Bags','wbj-wb-shoulder',2),
    ('wbj-womens-bags','Clutches','wbj-wb-clutches',3),
    ('wbj-womens-bags','Tote Bags','wbj-wb-tote',4),
    ('wbj-fashion-jewellery','Earrings','wbj-fj-earrings',1),
    ('wbj-fashion-jewellery','Necklaces','wbj-fj-necklaces',2),
    ('wbj-fashion-jewellery','Rings','wbj-fj-rings',3),
    ('wbj-fashion-jewellery','Bangles','wbj-fj-bangles',4),
    ('wbj-fashion-jewellery','Anklets','wbj-fj-anklets',5)
)
INSERT INTO public.categories (name, slug, parent_id, sort_order)
SELECT l.name, l.slug, p.id, l.sort_order
FROM l3 l
JOIN public.categories p ON p.slug = l.parent_slug
ON CONFLICT (slug) DO NOTHING;

UPDATE public.site_settings SET settings = '{
  "brand": {"name": "Bazar BD", "tagline": "Bangladesh''s premium online marketplace", "logo_url": "", "favicon_url": ""},
  "header": {
    "top_bar_enabled": true,
    "top_bar_text": "Free delivery on orders over ৳2000 — Shop now!",
    "nav_links": [
      {"label": "Home", "href": "/", "sort": 1},
      {"label": "Categories", "href": "/categories", "sort": 2},
      {"label": "Dropshipping", "href": "/dropshipping", "sort": 3},
      {"label": "Become a Vendor", "href": "/become-vendor", "sort": 4}
    ],
    "show_search": true, "show_wishlist": true, "show_cart": true, "show_account": true
  },
  "footer": {
    "columns": [
      {"title": "Customer Care", "links": [
        {"label": "Help Center", "href": "#"},
        {"label": "How to Buy", "href": "#"},
        {"label": "Returns & Refunds", "href": "#"},
        {"label": "Contact Us", "href": "#"}
      ]},
      {"title": "Bazar", "links": [
        {"label": "About Bazar", "href": "#"},
        {"label": "Careers", "href": "#"},
        {"label": "Bazar Blog", "href": "#"},
        {"label": "Press", "href": "#"}
      ]}
    ],
    "payment_badges": [
      {"label": "bKash", "bg": "#E2136E", "fg": "#ffffff"},
      {"label": "Nagad", "bg": "#EC1C24", "fg": "#ffffff"},
      {"label": "Rocket", "bg": "#8B2C8B", "fg": "#ffffff"},
      {"label": "VISA", "bg": "#1A1F71", "fg": "#F7B600"},
      {"label": "MasterCard", "bg": "#ffffff", "fg": "#EB001B"},
      {"label": "COD", "bg": "#16a34a", "fg": "#ffffff"}
    ],
    "app_links": {"app_store": "", "google_play": ""},
    "contact": {"email": "support@bazar-bd.com", "phone": "+880 1XXX-XXXXXX", "address": "Dhaka, Bangladesh"},
    "social": {"facebook": "", "instagram": "", "youtube": "", "twitter": ""},
    "copyright_text": "© Bazar Clone — Demo storefront built with Lovable."
  }
}'::jsonb WHERE id = 1;