
WITH l3(parent_slug, name, slug, sort_order) AS (
  VALUES
    -- Women's Fashion → Sarees
    ('womens-fashion-sarees','Silk Sarees','wf-sarees-silk',1),
    ('womens-fashion-sarees','Cotton Sarees','wf-sarees-cotton',2),
    ('womens-fashion-sarees','Jamdani','wf-sarees-jamdani',3),
    ('womens-fashion-sarees','Half Silk','wf-sarees-half-silk',4),
    ('womens-fashion-sarees','Georgette','wf-sarees-georgette',5),
    ('womens-fashion-sarees','Party Sarees','wf-sarees-party',6),
    ('womens-fashion-sarees','Wedding Sarees','wf-sarees-wedding',7),
    -- Women's Fashion → Salwar Kameez
    ('womens-fashion-salwar-kameez','Unstitched','wf-sk-unstitched',1),
    ('womens-fashion-salwar-kameez','Stitched','wf-sk-stitched',2),
    ('womens-fashion-salwar-kameez','Pakistani','wf-sk-pakistani',3),
    ('womens-fashion-salwar-kameez','Indian','wf-sk-indian',4),
    ('womens-fashion-salwar-kameez','Party Wear','wf-sk-party',5),
    -- Women's Fashion → Muslim Wear
    ('womens-fashion-muslim-wear','Abayas','wf-mw-abayas',1),
    ('womens-fashion-muslim-wear','Burqas','wf-mw-burqas',2),
    ('womens-fashion-muslim-wear','Hijabs','wf-mw-hijabs',3),
    ('womens-fashion-muslim-wear','Prayer Dresses','wf-mw-prayer',4),
    -- Women's Fashion → Tops
    ('womens-fashion-tops','T-Shirts','wf-tops-tshirts',1),
    ('womens-fashion-tops','Blouses','wf-tops-blouses',2),
    ('womens-fashion-tops','Tank Tops','wf-tops-tanks',3),
    ('womens-fashion-tops','Fatuas','wf-tops-fatuas',4),
    -- Women's Fashion → Shoes
    ('womens-fashion-shoes','Heels','wf-shoes-heels',1),
    ('womens-fashion-shoes','Flats','wf-shoes-flats',2),
    ('womens-fashion-shoes','Boots','wf-shoes-boots',3),
    ('womens-fashion-shoes','Sneakers','wf-shoes-sneakers',4),
    ('womens-fashion-shoes','Loafers','wf-shoes-loafers',5),

    -- Men's Fashion → T-Shirts
    ('mens-fashion-tshirts','Half Sleeve','mf-tshirts-half',1),
    ('mens-fashion-tshirts','Full Sleeve','mf-tshirts-full',2),
    ('mens-fashion-tshirts','Graphic Tees','mf-tshirts-graphic',3),
    ('mens-fashion-tshirts','Plain Tees','mf-tshirts-plain',4),
    -- Men's Fashion → Shirts
    ('mens-fashion-shirts','Formal Shirts','mf-shirts-formal',1),
    ('mens-fashion-shirts','Casual Shirts','mf-shirts-casual',2),
    ('mens-fashion-shirts','Denim Shirts','mf-shirts-denim',3),
    ('mens-fashion-shirts','Printed Shirts','mf-shirts-printed',4),
    -- Men's Fashion → Panjabi
    ('mens-fashion-panjabi','Cotton Panjabi','mf-panjabi-cotton',1),
    ('mens-fashion-panjabi','Silk Panjabi','mf-panjabi-silk',2),
    ('mens-fashion-panjabi','Eid Panjabi','mf-panjabi-eid',3),
    ('mens-fashion-panjabi','Kabli','mf-panjabi-kabli',4),
    -- Men's Fashion → Pants / Jeans
    ('mens-fashion-pants','Formal Pants','mf-pants-formal',1),
    ('mens-fashion-pants','Chinos','mf-pants-chinos',2),
    ('mens-fashion-pants','Cargo Pants','mf-pants-cargo',3),
    ('mens-fashion-pants','Joggers','mf-pants-joggers',4),
    ('mens-fashion-jeans','Slim Fit','mf-jeans-slim',1),
    ('mens-fashion-jeans','Regular Fit','mf-jeans-regular',2),
    ('mens-fashion-jeans','Skinny','mf-jeans-skinny',3),
    ('mens-fashion-jeans','Straight','mf-jeans-straight',4),
    -- Men's Fashion → Formal Shoes / Sneakers
    ('mens-fashion-formal-shoes','Oxfords','mf-fs-oxfords',1),
    ('mens-fashion-formal-shoes','Loafers','mf-fs-loafers',2),
    ('mens-fashion-formal-shoes','Derby','mf-fs-derby',3),
    ('mens-fashion-sneakers','Running','mf-sneakers-running',1),
    ('mens-fashion-sneakers','Casual','mf-sneakers-casual',2),
    ('mens-fashion-sneakers','High Tops','mf-sneakers-hightop',3),

    -- Electronic Devices → Mobiles
    ('ed-mobiles','Samsung','ed-mobiles-samsung',1),
    ('ed-mobiles','Xiaomi','ed-mobiles-xiaomi',2),
    ('ed-mobiles','Realme','ed-mobiles-realme',3),
    ('ed-mobiles','Oppo','ed-mobiles-oppo',4),
    ('ed-mobiles','Vivo','ed-mobiles-vivo',5),
    ('ed-mobiles','Apple iPhone','ed-mobiles-iphone',6),
    ('ed-mobiles','Infinix','ed-mobiles-infinix',7),
    ('ed-mobiles','Tecno','ed-mobiles-tecno',8),
    ('ed-mobiles','Nokia','ed-mobiles-nokia',9),
    ('ed-mobiles','Walton','ed-mobiles-walton',10),
    ('ed-mobiles','Symphony','ed-mobiles-symphony',11),
    -- Tablets
    ('ed-tablets','Samsung Tablets','ed-tablets-samsung',1),
    ('ed-tablets','Apple iPad','ed-tablets-ipad',2),
    ('ed-tablets','Lenovo Tablets','ed-tablets-lenovo',3),
    ('ed-tablets','Xiaomi Tablets','ed-tablets-xiaomi',4),
    ('ed-tablets','Huawei Tablets','ed-tablets-huawei',5),
    -- Laptops
    ('ed-laptops','HP','ed-laptops-hp',1),
    ('ed-laptops','Dell','ed-laptops-dell',2),
    ('ed-laptops','Lenovo','ed-laptops-lenovo',3),
    ('ed-laptops','Asus','ed-laptops-asus',4),
    ('ed-laptops','Acer','ed-laptops-acer',5),
    ('ed-laptops','Apple MacBook','ed-laptops-macbook',6),
    ('ed-laptops','MSI','ed-laptops-msi',7),
    ('ed-laptops','Walton Laptops','ed-laptops-walton',8),
    ('ed-laptops','Gaming Laptops','ed-laptops-gaming',9),
    -- Smart Watches
    ('ed-smartwatch','Apple Watch','ed-sw-apple',1),
    ('ed-smartwatch','Samsung Galaxy Watch','ed-sw-samsung',2),
    ('ed-smartwatch','Xiaomi Mi Band','ed-sw-xiaomi',3),
    ('ed-smartwatch','Amazfit','ed-sw-amazfit',4),
    ('ed-smartwatch','Fitness Trackers','ed-sw-fitness',5),

    -- Electronic Accessories → Headphones & Earbuds
    ('ea-headphones','Wireless Earbuds','ea-hp-wireless-earbuds',1),
    ('ea-headphones','Wired Earphones','ea-hp-wired',2),
    ('ea-headphones','Over-Ear Headphones','ea-hp-overear',3),
    ('ea-headphones','Gaming Headsets','ea-hp-gaming',4),
    ('ea-headphones','Neckband Earphones','ea-hp-neckband',5),
    ('ea-headphones','Bluetooth Headsets','ea-hp-bt-headset',6),
    -- Power Banks / Chargers
    ('ea-power-banks','10000 mAh','ea-pb-10000',1),
    ('ea-power-banks','20000 mAh','ea-pb-20000',2),
    ('ea-power-banks','Fast Charging Power Banks','ea-pb-fast',3),
    ('ea-power-banks','Solar Power Banks','ea-pb-solar',4),
    ('ea-chargers','Fast Chargers','ea-chargers-fast',1),
    ('ea-chargers','Wireless Chargers','ea-chargers-wireless',2),
    ('ea-chargers','USB-C Cables','ea-chargers-usbc',3),
    ('ea-chargers','Lightning Cables','ea-chargers-lightning',4),
    ('ea-chargers','Micro USB Cables','ea-chargers-micro',5),

    -- TV & Home Appliances → Televisions / AC / Fridge / Fans
    ('tvha-tvs','Smart TVs','tvha-tvs-smart',1),
    ('tvha-tvs','4K UHD TVs','tvha-tvs-4k',2),
    ('tvha-tvs','LED TVs','tvha-tvs-led',3),
    ('tvha-tvs','32 Inch','tvha-tvs-32',4),
    ('tvha-tvs','43 Inch','tvha-tvs-43',5),
    ('tvha-tvs','55 Inch','tvha-tvs-55',6),
    ('tvha-tvs','65 Inch','tvha-tvs-65',7),
    ('tvha-ac','Split AC','tvha-ac-split',1),
    ('tvha-ac','Inverter AC','tvha-ac-inverter',2),
    ('tvha-ac','1 Ton','tvha-ac-1ton',3),
    ('tvha-ac','1.5 Ton','tvha-ac-1-5ton',4),
    ('tvha-ac','2 Ton','tvha-ac-2ton',5),
    ('tvha-fridge','Double Door','tvha-fridge-double',1),
    ('tvha-fridge','Single Door','tvha-fridge-single',2),
    ('tvha-fridge','Side By Side','tvha-fridge-sbs',3),
    ('tvha-fridge','Mini Fridge','tvha-fridge-mini',4),
    ('tvha-fans','Ceiling Fans','tvha-fans-ceiling',1),
    ('tvha-fans','Table Fans','tvha-fans-table',2),
    ('tvha-fans','Pedestal Fans','tvha-fans-pedestal',3),
    ('tvha-fans','Rechargeable Fans','tvha-fans-rechargeable',4),
    ('tvha-fans','Exhaust Fans','tvha-fans-exhaust',5),

    -- Health & Beauty → Skin Care / Makeup / Hair Care
    ('hb-skincare','Face Wash','hb-skin-facewash',1),
    ('hb-skincare','Moisturizers','hb-skin-moisturizer',2),
    ('hb-skincare','Sunscreen','hb-skin-sunscreen',3),
    ('hb-skincare','Face Serums','hb-skin-serum',4),
    ('hb-skincare','Face Masks','hb-skin-mask',5),
    ('hb-skincare','Toners','hb-skin-toner',6),
    ('hb-skincare','Acne Treatment','hb-skin-acne',7),
    ('hb-makeup','Lipstick','hb-mk-lipstick',1),
    ('hb-makeup','Foundation','hb-mk-foundation',2),
    ('hb-makeup','Eyeliner','hb-mk-eyeliner',3),
    ('hb-makeup','Mascara','hb-mk-mascara',4),
    ('hb-makeup','Eyeshadow','hb-mk-eyeshadow',5),
    ('hb-makeup','Blush','hb-mk-blush',6),
    ('hb-makeup','Nail Polish','hb-mk-nailpolish',7),
    ('hb-haircare','Shampoo','hb-hair-shampoo',1),
    ('hb-haircare','Conditioner','hb-hair-conditioner',2),
    ('hb-haircare','Hair Oil','hb-hair-oil',3),
    ('hb-haircare','Hair Mask','hb-hair-mask',4),
    ('hb-haircare','Hair Color','hb-hair-color',5),

    -- Home & Lifestyle → Furniture / Kitchenware
    ('home-furniture','Sofas','home-furn-sofa',1),
    ('home-furniture','Beds','home-furn-bed',2),
    ('home-furniture','Dining Tables','home-furn-dining',3),
    ('home-furniture','Wardrobes','home-furn-wardrobe',4),
    ('home-furniture','Office Chairs','home-furn-office-chair',5),
    ('home-furniture','Study Tables','home-furn-study',6),
    ('home-furniture','Shoe Racks','home-furn-shoerack',7),
    ('home-kitchenware','Pressure Cookers','home-kw-pressure',1),
    ('home-kitchenware','Rice Cookers','home-kw-rice',2),
    ('home-kitchenware','Non-Stick Pans','home-kw-nonstick',3),
    ('home-kitchenware','Knives','home-kw-knives',4),
    ('home-kitchenware','Water Bottles','home-kw-bottles',5),
    ('home-kitchenware','Lunch Boxes','home-kw-lunchbox',6),

    -- Groceries & Pets → Beverages / Snacks
    ('gp-beverages','Tea','gp-bev-tea',1),
    ('gp-beverages','Coffee','gp-bev-coffee',2),
    ('gp-beverages','Soft Drinks','gp-bev-softdrinks',3),
    ('gp-beverages','Juices','gp-bev-juices',4),
    ('gp-beverages','Energy Drinks','gp-bev-energy',5),
    ('gp-beverages','Water','gp-bev-water',6),
    ('gp-snacks','Chips & Crisps','gp-snacks-chips',1),
    ('gp-snacks','Biscuits & Cookies','gp-snacks-biscuits',2),
    ('gp-snacks','Chocolates','gp-snacks-chocolate',3),
    ('gp-snacks','Nuts & Dry Fruits','gp-snacks-nuts',4),
    ('gp-snacks','Instant Noodles','gp-snacks-noodles',5),
    ('gp-cooking','Cooking Oil','gp-cook-oil',1),
    ('gp-cooking','Spices','gp-cook-spices',2),
    ('gp-cooking','Salt & Sugar','gp-cook-salt-sugar',3),
    ('gp-cooking','Sauces & Condiments','gp-cook-sauces',4),
    ('gp-cooking','Ghee & Butter','gp-cook-ghee',5),

    -- Sports & Outdoor → Cricket / Football / Fitness
    ('so-cricket','Cricket Bats','so-cricket-bat',1),
    ('so-cricket','Cricket Balls','so-cricket-ball',2),
    ('so-cricket','Cricket Gloves','so-cricket-gloves',3),
    ('so-cricket','Cricket Pads','so-cricket-pads',4),
    ('so-cricket','Cricket Helmets','so-cricket-helmet',5),
    ('so-football','Footballs','so-football-ball',1),
    ('so-football','Football Boots','so-football-boots',2),
    ('so-football','Football Jerseys','so-football-jersey',3),
    ('so-football','Shin Guards','so-football-shin',4),
    ('so-fitness','Dumbbells','so-fit-dumbbells',1),
    ('so-fitness','Yoga Mats','so-fit-yoga',2),
    ('so-fitness','Treadmills','so-fit-treadmill',3),
    ('so-fitness','Resistance Bands','so-fit-bands',4),
    ('so-fitness','Skipping Ropes','so-fit-skipping',5),

    -- Mother & Baby → Diapers / Baby Clothing / Toys
    ('mb-diapers','Newborn Diapers','mb-diapers-newborn',1),
    ('mb-diapers','Small Diapers','mb-diapers-small',2),
    ('mb-diapers','Medium Diapers','mb-diapers-medium',3),
    ('mb-diapers','Large Diapers','mb-diapers-large',4),
    ('mb-diapers','Pants Style Diapers','mb-diapers-pants',5),
    ('mb-baby-clothing','Baby Boy Clothing','mb-clothing-boy',1),
    ('mb-baby-clothing','Baby Girl Clothing','mb-clothing-girl',2),
    ('mb-baby-clothing','Newborn Sets','mb-clothing-newborn',3),
    ('mb-baby-clothing','Baby Winter Wear','mb-clothing-winter',4),
    ('mb-toys-games','Educational Toys','mb-toys-educational',1),
    ('mb-toys-games','Remote Control Toys','mb-toys-rc',2),
    ('mb-toys-games','Dolls & Plush','mb-toys-dolls',3),
    ('mb-toys-games','Building Blocks','mb-toys-blocks',4),
    ('mb-toys-games','Puzzles','mb-toys-puzzles',5),
    ('mb-toys-games','Outdoor Toys','mb-toys-outdoor',6),

    -- Automotive & Motorbike → Helmets / Parts
    ('am-helmets','Full Face Helmets','am-helmet-fullface',1),
    ('am-helmets','Half Helmets','am-helmet-half',2),
    ('am-helmets','Modular Helmets','am-helmet-modular',3),
    ('am-helmets','Kids Helmets','am-helmet-kids',4),
    ('am-moto-parts','Engine Parts','am-moto-parts-engine',1),
    ('am-moto-parts','Chain & Sprocket','am-moto-parts-chain',2),
    ('am-moto-parts','Brake Parts','am-moto-parts-brake',3),
    ('am-moto-parts','Lights & Indicators','am-moto-parts-lights',4),
    ('am-moto-parts','Mirrors','am-moto-parts-mirrors',5),

    -- Watches, Bags & Jewellery → Men's / Women's Watches
    ('wbj-mens-watches','Analog','wbj-mw-analog',1),
    ('wbj-mens-watches','Digital','wbj-mw-digital',2),
    ('wbj-mens-watches','Chronograph','wbj-mw-chrono',3),
    ('wbj-mens-watches','Leather Strap','wbj-mw-leather',4),
    ('wbj-mens-watches','Steel Strap','wbj-mw-steel',5),
    ('wbj-womens-watches','Analog','wbj-ww-analog',1),
    ('wbj-womens-watches','Digital','wbj-ww-digital',2),
    ('wbj-womens-watches','Bracelet Watches','wbj-ww-bracelet',3),
    ('wbj-womens-bags','Handbags','wbj-wb-handbags',1),
    ('wbj-womens-bags','Shoulder Bags','wbj-wb-shoulder',2),
    ('wbj-womens-bags','Clutches','wbj-wb-clutches',3),
    ('wbj-womens-bags','Tote Bags','wbj-wb-tote',4),
    ('wbj-fashion-jewellery','Earrings','wbj-fj-earrings',1),
    ('wbj-fashion-jewellery','Necklaces','wbj-fj-necklaces',2),
    ('wbj-fashion-jewellery','Rings','wbj-fj-rings',3),
    ('wbj-fashion-jewellery','Bangles','wbj-fj-bangles',4),
    ('wbj-fashion-jewellery','Anklets','wbj-fj-anklets',5)
)
INSERT INTO public.categories (name, slug, parent_id, sort_order)
SELECT l.name, l.slug, p.id, l.sort_order
FROM l3 l
JOIN public.categories p ON p.slug = l.parent_slug
ON CONFLICT (slug) DO NOTHING;
