// Bangladesh: 64 districts with their upazilas + metropolitan thanas (DMP/CMP/KMP/RMP/SMP/BMP/RpMP/GMP).
// Source: Bangladesh Police + BBS administrative lists (2024).
export const BD_LOCATIONS: Record<string, string[]> = {
  Bagerhat: ["Bagerhat Sadar","Chitalmari","Fakirhat","Kachua","Mollahat","Mongla","Morrelganj","Rampal","Sarankhola"],
  Bandarban: ["Alikadam","Bandarban Sadar","Lama","Naikhongchhari","Rowangchhari","Ruma","Thanchi"],
  Barguna: ["Amtali","Bamna","Barguna Sadar","Betagi","Patharghata","Taltali"],
  Barishal: ["Agailjhara","Babuganj","Bakerganj","Banaripara","Barishal Sadar","Gaurnadi","Hizla","Mehendiganj","Muladi","Wazirpur","Kotwali (Barishal Metro)","Airport (Barishal Metro)","Bandar (Barishal Metro)","Kawnia (Barishal Metro)"],
  Bhola: ["Bhola Sadar","Burhanuddin","Char Fasson","Daulatkhan","Lalmohan","Manpura","Tazumuddin"],
  Bogura: ["Adamdighi","Bogura Sadar","Dhunat","Dhupchanchia","Gabtali","Kahaloo","Nandigram","Sariakandi","Shajahanpur","Sherpur","Shibganj","Sonatala"],
  Brahmanbaria: ["Akhaura","Ashuganj","Bancharampur","Bijoynagar","Brahmanbaria Sadar","Kasba","Nabinagar","Nasirnagar","Sarail"],
  Chandpur: ["Chandpur Sadar","Faridganj","Haimchar","Haziganj","Kachua","Matlab Dakshin","Matlab Uttar","Shahrasti"],
  Chapainawabganj: ["Bholahat","Chapainawabganj Sadar","Gomastapur","Nachole","Shibganj"],
  Chattogram: ["Anwara","Banshkhali","Boalkhali","Chandanaish","Fatikchhari","Hathazari","Karnaphuli","Lohagara","Mirsharai","Patiya","Rangunia","Raozan","Sandwip","Satkania","Sitakunda",
    "Kotwali (CMP)","Panchlaish (CMP)","Double Mooring (CMP)","Pahartali (CMP)","Halishahar (CMP)","Chandgaon (CMP)","Bakalia (CMP)","Bandar (CMP)","Patenga (CMP)","Khulshi (CMP)","Chawkbazar (CMP)","Sadarghat (CMP)","EPZ (CMP)","Karnaphuli (CMP)","Akbarshah (CMP)","Bayezid Bostami (CMP)"],
  Chuadanga: ["Alamdanga","Chuadanga Sadar","Damurhuda","Jibannagar"],
  Cumilla: ["Barura","Brahmanpara","Burichang","Chandina","Chauddagram","Cumilla Adarsha Sadar","Cumilla Sadar Dakshin","Daudkandi","Debidwar","Homna","Laksam","Lalmai","Manoharganj","Meghna","Muradnagar","Nangalkot","Titas","Kotwali (Cumilla Metro)","Sadar Dakshin (Cumilla Metro)"],
  "Cox's Bazar": ["Chakaria","Cox's Bazar Sadar","Kutubdia","Maheshkhali","Pekua","Ramu","Teknaf","Ukhia","Eidgaon"],
  Dhaka: [
    "Dhamrai","Dohar","Keraniganj","Nawabganj","Savar",
    // Dhaka Metropolitan Police (DMP) thanas
    "Adabor (DMP)","Airport (DMP)","Badda (DMP)","Bangshal (DMP)","Bhasantek (DMP)","Bhatara (DMP)","Biman Bandar (DMP)","Cantonment (DMP)","Chawkbazar (DMP)","Dakshinkhan (DMP)","Darus Salam (DMP)","Demra (DMP)","Dhanmondi (DMP)","Gendaria (DMP)","Gulshan (DMP)","Hatirjheel (DMP)","Hazaribagh (DMP)","Jatrabari (DMP)","Kadamtali (DMP)","Kafrul (DMP)","Kalabagan (DMP)","Kamrangirchar (DMP)","Khilgaon (DMP)","Khilkhet (DMP)","Kotwali (DMP)","Lalbagh (DMP)","Mirpur Model (DMP)","Mohammadpur (DMP)","Motijheel (DMP)","Mugda (DMP)","New Market (DMP)","Pallabi (DMP)","Paltan (DMP)","Ramna (DMP)","Rampura (DMP)","Rupnagar (DMP)","Sabujbagh (DMP)","Shah Ali (DMP)","Shahbagh (DMP)","Shahjahanpur (DMP)","Sher-e-Bangla Nagar (DMP)","Shyampur (DMP)","Sutrapur (DMP)","Tejgaon (DMP)","Tejgaon Industrial (DMP)","Turag (DMP)","Uttara East (DMP)","Uttara West (DMP)","Uttarkhan (DMP)","Wari (DMP)"
  ],
  Dinajpur: ["Birampur","Birganj","Biral","Bochaganj","Chirirbandar","Dinajpur Sadar","Phulbari","Ghoraghat","Hakimpur","Kaharole","Khansama","Nawabganj","Parbatipur"],
  Faridpur: ["Alfadanga","Bhanga","Boalmari","Charbhadrasan","Faridpur Sadar","Madhukhali","Nagarkanda","Sadarpur","Saltha"],
  Feni: ["Chhagalnaiya","Daganbhuiyan","Feni Sadar","Fulgazi","Parshuram","Sonagazi"],
  Gaibandha: ["Phulchhari","Gaibandha Sadar","Gobindaganj","Palashbari","Sadullapur","Saghata","Sundarganj"],
  Gazipur: ["Gazipur Sadar","Kaliakair","Kaliganj","Kapasia","Sreepur","Joydebpur (GMP)","Basan (GMP)","Konabari (GMP)","Kashimpur (GMP)","Gacha (GMP)","Sadar (GMP)","Tongi East (GMP)","Tongi West (GMP)"],
  Gopalganj: ["Gopalganj Sadar","Kashiani","Kotalipara","Muksudpur","Tungipara"],
  Habiganj: ["Ajmiriganj","Bahubal","Baniyachong","Chunarughat","Habiganj Sadar","Lakhai","Madhabpur","Nabiganj","Shayestaganj"],
  Jamalpur: ["Bakshiganj","Dewanganj","Islampur","Jamalpur Sadar","Madarganj","Melandaha","Sarishabari"],
  Jashore: ["Abhaynagar","Bagherpara","Chaugachha","Jhikargachha","Keshabpur","Jashore Sadar","Manirampur","Sharsha"],
  Jhalokati: ["Jhalokati Sadar","Kathalia","Nalchity","Rajapur"],
  Jhenaidah: ["Harinakunda","Jhenaidah Sadar","Kaliganj","Kotchandpur","Maheshpur","Shailkupa"],
  Joypurhat: ["Akkelpur","Joypurhat Sadar","Kalai","Khetlal","Panchbibi"],
  Khagrachhari: ["Dighinala","Guimara","Khagrachhari Sadar","Lakshmichhari","Mahalchhari","Manikchhari","Matiranga","Panchhari","Ramgarh"],
  Khulna: ["Batiaghata","Dacope","Dighalia","Dumuria","Koyra","Paikgachha","Phultala","Rupsa","Terokhada",
    "Kotwali (KMP)","Sonadanga (KMP)","Khalishpur (KMP)","Daulatpur (KMP)","Khan Jahan Ali (KMP)","Aranghata (KMP)","Harintana (KMP)","Labanchara (KMP)"],
  Kishoreganj: ["Astagram","Bajitpur","Bhairab","Hossainpur","Itna","Karimganj","Katiadi","Kishoreganj Sadar","Kuliarchar","Mithamain","Nikli","Pakundia","Tarail"],
  Kurigram: ["Bhurungamari","Char Rajibpur","Chilmari","Phulbari","Kurigram Sadar","Nageshwari","Rajarhat","Raomari","Ulipur"],
  Kushtia: ["Bheramara","Daulatpur","Khoksa","Kumarkhali","Kushtia Sadar","Mirpur"],
  Lakshmipur: ["Kamalnagar","Lakshmipur Sadar","Raipur","Ramganj","Ramgati"],
  Lalmonirhat: ["Aditmari","Hatibandha","Kaliganj","Lalmonirhat Sadar","Patgram"],
  Madaripur: ["Dasar","Kalkini","Madaripur Sadar","Rajoir","Shibchar"],
  Magura: ["Magura Sadar","Mohammadpur","Shalikha","Sreepur"],
  Manikganj: ["Daulatpur","Ghior","Harirampur","Manikganj Sadar","Saturia","Shibalaya","Singair"],
  Meherpur: ["Gangni","Meherpur Sadar","Mujibnagar"],
  Moulvibazar: ["Barlekha","Juri","Kamalganj","Kulaura","Moulvibazar Sadar","Rajnagar","Sreemangal"],
  Munshiganj: ["Gazaria","Lohajang","Munshiganj Sadar","Sirajdikhan","Sreenagar","Tongibari"],
  Mymensingh: ["Bhaluka","Dhobaura","Phulbaria","Fulpur","Gaffargaon","Gauripur","Haluaghat","Ishwarganj","Mymensingh Sadar","Muktagachha","Nandail","Trishal","Tarakanda","Kotwali (MMP)","Kotwali Model (MMP)"],
  Naogaon: ["Atrai","Badalgachhi","Dhamoirhat","Manda","Mohadevpur","Naogaon Sadar","Niamatpur","Patnitala","Porsha","Raninagar","Sapahar"],
  Narail: ["Kalia","Lohagara","Narail Sadar"],
  Narayanganj: ["Araihazar","Bandar","Narayanganj Sadar","Rupganj","Sonargaon","Fatullah","Siddhirganj"],
  Narsingdi: ["Belabo","Monohardi","Narsingdi Sadar","Palash","Raipura","Shibpur"],
  Natore: ["Bagatipara","Baraigram","Gurudaspur","Lalpur","Naldanga","Natore Sadar","Singra"],
  Netrokona: ["Atpara","Barhatta","Durgapur","Khaliajuri","Kalmakanda","Kendua","Madan","Mohanganj","Netrokona Sadar","Purbadhala"],
  Nilphamari: ["Dimla","Domar","Jaldhaka","Kishoreganj","Nilphamari Sadar","Saidpur"],
  Noakhali: ["Begumganj","Chatkhil","Companiganj","Hatiya","Kabirhat","Noakhali Sadar","Senbagh","Sonaimuri","Subarnachar"],
  Pabna: ["Atgharia","Bera","Bhangura","Chatmohar","Faridpur","Ishwardi","Pabna Sadar","Santhia","Sujanagar"],
  Panchagarh: ["Atwari","Boda","Debiganj","Panchagarh Sadar","Tetulia"],
  Patuakhali: ["Bauphal","Dashmina","Dumki","Galachipa","Kalapara","Mirzaganj","Patuakhali Sadar","Rangabali"],
  Pirojpur: ["Bhandaria","Kawkhali","Mathbaria","Nazirpur","Nesarabad","Pirojpur Sadar","Zianagar"],
  Rajbari: ["Baliakandi","Goalandaghat","Kalukhali","Pangsha","Rajbari Sadar"],
  Rajshahi: ["Bagha","Bagmara","Charghat","Durgapur","Godagari","Mohanpur","Paba","Puthia","Tanore",
    "Boalia (RMP)","Motihar (RMP)","Rajpara (RMP)","Shah Makhdum (RMP)","Chandrima (RMP)","Kashiadanga (RMP)","Kornohar (RMP)","Damkura (RMP)","Katakhali (RMP)","Airport (RMP)","Belpukur (RMP)","Karnahar (RMP)"],
  Rangamati: ["Baghaichhari","Barkal","Belaichhari","Juraichhari","Kaptai","Kawkhali","Langadu","Naniarchar","Rajasthali","Rangamati Sadar"],
  Rangpur: ["Badarganj","Gangachara","Kaunia","Mithapukur","Pirgachha","Pirganj","Rangpur Sadar","Taraganj",
    "Kotwali (RpMP)","Mahiganj (RpMP)","Tajhat (RpMP)","Parshuram (RpMP)","Haragachh (RpMP)","Hajirhat (RpMP)"],
  Satkhira: ["Assasuni","Debhata","Kalaroa","Kaliganj","Satkhira Sadar","Shyamnagar","Tala"],
  Shariatpur: ["Bhedarganj","Damudya","Gosairhat","Naria","Shariatpur Sadar","Zajira"],
  Sherpur: ["Jhenaigati","Nakla","Nalitabari","Sherpur Sadar","Sreebardi"],
  Sirajganj: ["Belkuchi","Chauhali","Kamarkhanda","Kazipur","Raiganj","Shahjadpur","Sirajganj Sadar","Tarash","Ullapara"],
  Sunamganj: ["Bishwamvarpur","Chhatak","Derai","Dharmapasha","Dowarabazar","Jagannathpur","Jamalganj","Sulla","Sunamganj Sadar","Tahirpur","Shantiganj","Madhyanagar"],
  Sylhet: ["Balaganj","Beanibazar","Bishwanath","Companiganj","Dakshin Surma","Fenchuganj","Golapganj","Gowainghat","Jaintiapur","Kanaighat","Sylhet Sadar","Zakiganj","Osmaninagar",
    "Kotwali (SMP)","Jalalabad (SMP)","Airport (SMP)","South Surma (SMP)","Shah Poran (SMP)","Moglabazar (SMP)"],
  Tangail: ["Basail","Bhuapur","Delduar","Dhanbari","Ghatail","Gopalpur","Kalihati","Madhupur","Mirzapur","Nagarpur","Sakhipur","Tangail Sadar"],
  Thakurgaon: ["Baliadangi","Haripur","Pirganj","Ranisankail","Thakurgaon Sadar"],
};

export const BD_DISTRICTS = Object.keys(BD_LOCATIONS).sort();
