/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SysX7k9ControlRouteImport } from './routes/sys-x7k9-control'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DropshippingRouteImport } from './routes/dropshipping'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BecomeVendorRouteImport } from './routes/become-vendor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as SysX7k9ControlIndexRouteImport } from './routes/sys-x7k9-control.index'
import { Route as DropshippingIndexRouteImport } from './routes/dropshipping.index'
import { Route as VendorStoreRouteImport } from './routes/vendor.store'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as SysX7k9ControlVendorsRouteImport } from './routes/sys-x7k9-control.vendors'
import { Route as SysX7k9ControlStaffRouteImport } from './routes/sys-x7k9-control.staff'
import { Route as SysX7k9ControlSiteCustomizationRouteImport } from './routes/sys-x7k9-control.site-customization'
import { Route as SysX7k9ControlShippingRouteImport } from './routes/sys-x7k9-control.shipping'
import { Route as SysX7k9ControlSettingsRouteImport } from './routes/sys-x7k9-control.settings'
import { Route as SysX7k9ControlReviewsRouteImport } from './routes/sys-x7k9-control.reviews'
import { Route as SysX7k9ControlRelatedClicksRouteImport } from './routes/sys-x7k9-control.related-clicks'
import { Route as SysX7k9ControlPromotionsRouteImport } from './routes/sys-x7k9-control.promotions'
import { Route as SysX7k9ControlProductsRouteImport } from './routes/sys-x7k9-control.products'
import { Route as SysX7k9ControlPasswordResetsRouteImport } from './routes/sys-x7k9-control.password-resets'
import { Route as SysX7k9ControlOrdersRouteImport } from './routes/sys-x7k9-control.orders'
import { Route as SysX7k9ControlOffersRouteImport } from './routes/sys-x7k9-control.offers'
import { Route as SysX7k9ControlLocationsCheckRouteImport } from './routes/sys-x7k9-control.locations-check'
import { Route as SysX7k9ControlDsDiagnosticRouteImport } from './routes/sys-x7k9-control.ds-diagnostic'
import { Route as SysX7k9ControlDropshippingSettingsRouteImport } from './routes/sys-x7k9-control.dropshipping-settings'
import { Route as SysX7k9ControlDropshippingPayoutsRouteImport } from './routes/sys-x7k9-control.dropshipping-payouts'
import { Route as SysX7k9ControlDropshippingEarningsRouteImport } from './routes/sys-x7k9-control.dropshipping-earnings'
import { Route as SysX7k9ControlDropshippingAnnouncementsRouteImport } from './routes/sys-x7k9-control.dropshipping-announcements'
import { Route as SysX7k9ControlDropshippersRouteImport } from './routes/sys-x7k9-control.dropshippers'
import { Route as SysX7k9ControlCustomersRouteImport } from './routes/sys-x7k9-control.customers'
import { Route as SysX7k9ControlCouponsRouteImport } from './routes/sys-x7k9-control.coupons'
import { Route as SysX7k9ControlCategoriesRouteImport } from './routes/sys-x7k9-control.categories'
import { Route as SysX7k9ControlBannersRouteImport } from './routes/sys-x7k9-control.banners'
import { Route as SysX7k9ControlAuditLogsRouteImport } from './routes/sys-x7k9-control.audit-logs'
import { Route as SysX7k9ControlAnalyticsRouteImport } from './routes/sys-x7k9-control.analytics'
import { Route as SysX7k9ControlAffiliatesRouteImport } from './routes/sys-x7k9-control.affiliates'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as DsSlugRouteImport } from './routes/ds.$slug'
import { Route as DropshippingSettingsRouteImport } from './routes/dropshipping.settings'
import { Route as DropshippingProductsRouteImport } from './routes/dropshipping.products'
import { Route as DropshippingPayoutsRouteImport } from './routes/dropshipping.payouts'
import { Route as DropshippingOrdersRouteImport } from './routes/dropshipping.orders'
import { Route as DropshippingMarketingRouteImport } from './routes/dropshipping.marketing'
import { Route as DropshippingLinksRouteImport } from './routes/dropshipping.links'
import { Route as DropshippingEarningsRouteImport } from './routes/dropshipping.earnings'
import { Route as DropshippingApplyRouteImport } from './routes/dropshipping.apply'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as SysX7k9ControlOrdersIdRouteImport } from './routes/sys-x7k9-control.orders_.$id'
import { Route as DropshippingViewImportIdRouteImport } from './routes/dropshipping.view.$importId'
import { Route as DropshippingOrderImportIdRouteImport } from './routes/dropshipping.order.$importId'
import { Route as DropshippingOrderConfirmationOrderIdRouteImport } from './routes/dropshipping.order-confirmation.$orderId'
import { Route as ApiPublicRedeployRouteImport } from './routes/api/public/redeploy'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SysX7k9ControlRoute = SysX7k9ControlRouteImport.update({
  id: '/sys-x7k9-control',
  path: '/sys-x7k9-control',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DropshippingRoute = DropshippingRouteImport.update({
  id: '/dropshipping',
  path: '/dropshipping',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeVendorRoute = BecomeVendorRouteImport.update({
  id: '/become-vendor',
  path: '/become-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const SysX7k9ControlIndexRoute = SysX7k9ControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const DropshippingIndexRoute = DropshippingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DropshippingRoute,
} as any)
const VendorStoreRoute = VendorStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const SysX7k9ControlVendorsRoute = SysX7k9ControlVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlStaffRoute = SysX7k9ControlStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlSiteCustomizationRoute =
  SysX7k9ControlSiteCustomizationRouteImport.update({
    id: '/site-customization',
    path: '/site-customization',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlShippingRoute = SysX7k9ControlShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlSettingsRoute = SysX7k9ControlSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlReviewsRoute = SysX7k9ControlReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlRelatedClicksRoute =
  SysX7k9ControlRelatedClicksRouteImport.update({
    id: '/related-clicks',
    path: '/related-clicks',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlPromotionsRoute =
  SysX7k9ControlPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlProductsRoute = SysX7k9ControlProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlPasswordResetsRoute =
  SysX7k9ControlPasswordResetsRouteImport.update({
    id: '/password-resets',
    path: '/password-resets',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlOrdersRoute = SysX7k9ControlOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlOffersRoute = SysX7k9ControlOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlLocationsCheckRoute =
  SysX7k9ControlLocationsCheckRouteImport.update({
    id: '/locations-check',
    path: '/locations-check',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlDsDiagnosticRoute =
  SysX7k9ControlDsDiagnosticRouteImport.update({
    id: '/ds-diagnostic',
    path: '/ds-diagnostic',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlDropshippingSettingsRoute =
  SysX7k9ControlDropshippingSettingsRouteImport.update({
    id: '/dropshipping-settings',
    path: '/dropshipping-settings',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlDropshippingPayoutsRoute =
  SysX7k9ControlDropshippingPayoutsRouteImport.update({
    id: '/dropshipping-payouts',
    path: '/dropshipping-payouts',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlDropshippingEarningsRoute =
  SysX7k9ControlDropshippingEarningsRouteImport.update({
    id: '/dropshipping-earnings',
    path: '/dropshipping-earnings',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlDropshippingAnnouncementsRoute =
  SysX7k9ControlDropshippingAnnouncementsRouteImport.update({
    id: '/dropshipping-announcements',
    path: '/dropshipping-announcements',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlDropshippersRoute =
  SysX7k9ControlDropshippersRouteImport.update({
    id: '/dropshippers',
    path: '/dropshippers',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlCustomersRoute = SysX7k9ControlCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlCouponsRoute = SysX7k9ControlCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlCategoriesRoute =
  SysX7k9ControlCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const SysX7k9ControlBannersRoute = SysX7k9ControlBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlAuditLogsRoute = SysX7k9ControlAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlAnalyticsRoute = SysX7k9ControlAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const SysX7k9ControlAffiliatesRoute =
  SysX7k9ControlAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => SysX7k9ControlRoute,
  } as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DsSlugRoute = DsSlugRouteImport.update({
  id: '/ds/$slug',
  path: '/ds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DropshippingSettingsRoute = DropshippingSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DropshippingRoute,
} as any)
const DropshippingProductsRoute = DropshippingProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DropshippingRoute,
} as any)
const DropshippingPayoutsRoute = DropshippingPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => DropshippingRoute,
} as any)
const DropshippingOrdersRoute = DropshippingOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DropshippingRoute,
} as any)
const DropshippingMarketingRoute = DropshippingMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => DropshippingRoute,
} as any)
const DropshippingLinksRoute = DropshippingLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DropshippingRoute,
} as any)
const DropshippingEarningsRoute = DropshippingEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DropshippingRoute,
} as any)
const DropshippingApplyRoute = DropshippingApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => DropshippingRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const SysX7k9ControlOrdersIdRoute = SysX7k9ControlOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => SysX7k9ControlRoute,
} as any)
const DropshippingViewImportIdRoute =
  DropshippingViewImportIdRouteImport.update({
    id: '/view/$importId',
    path: '/view/$importId',
    getParentRoute: () => DropshippingRoute,
  } as any)
const DropshippingOrderImportIdRoute =
  DropshippingOrderImportIdRouteImport.update({
    id: '/order/$importId',
    path: '/order/$importId',
    getParentRoute: () => DropshippingRoute,
  } as any)
const DropshippingOrderConfirmationOrderIdRoute =
  DropshippingOrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => DropshippingRoute,
  } as any)
const ApiPublicRedeployRoute = ApiPublicRedeployRouteImport.update({
  id: '/api/public/redeploy',
  path: '/api/public/redeploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/dropshipping': typeof DropshippingRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sys-x7k9-control': typeof SysX7k9ControlRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dropshipping/apply': typeof DropshippingApplyRoute
  '/dropshipping/earnings': typeof DropshippingEarningsRoute
  '/dropshipping/links': typeof DropshippingLinksRoute
  '/dropshipping/marketing': typeof DropshippingMarketingRoute
  '/dropshipping/orders': typeof DropshippingOrdersRoute
  '/dropshipping/payouts': typeof DropshippingPayoutsRoute
  '/dropshipping/products': typeof DropshippingProductsRoute
  '/dropshipping/settings': typeof DropshippingSettingsRoute
  '/ds/$slug': typeof DsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/p/$slug': typeof PSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$slug': typeof StoreSlugRoute
  '/sys-x7k9-control/affiliates': typeof SysX7k9ControlAffiliatesRoute
  '/sys-x7k9-control/analytics': typeof SysX7k9ControlAnalyticsRoute
  '/sys-x7k9-control/audit-logs': typeof SysX7k9ControlAuditLogsRoute
  '/sys-x7k9-control/banners': typeof SysX7k9ControlBannersRoute
  '/sys-x7k9-control/categories': typeof SysX7k9ControlCategoriesRoute
  '/sys-x7k9-control/coupons': typeof SysX7k9ControlCouponsRoute
  '/sys-x7k9-control/customers': typeof SysX7k9ControlCustomersRoute
  '/sys-x7k9-control/dropshippers': typeof SysX7k9ControlDropshippersRoute
  '/sys-x7k9-control/dropshipping-announcements': typeof SysX7k9ControlDropshippingAnnouncementsRoute
  '/sys-x7k9-control/dropshipping-earnings': typeof SysX7k9ControlDropshippingEarningsRoute
  '/sys-x7k9-control/dropshipping-payouts': typeof SysX7k9ControlDropshippingPayoutsRoute
  '/sys-x7k9-control/dropshipping-settings': typeof SysX7k9ControlDropshippingSettingsRoute
  '/sys-x7k9-control/ds-diagnostic': typeof SysX7k9ControlDsDiagnosticRoute
  '/sys-x7k9-control/locations-check': typeof SysX7k9ControlLocationsCheckRoute
  '/sys-x7k9-control/offers': typeof SysX7k9ControlOffersRoute
  '/sys-x7k9-control/orders': typeof SysX7k9ControlOrdersRoute
  '/sys-x7k9-control/password-resets': typeof SysX7k9ControlPasswordResetsRoute
  '/sys-x7k9-control/products': typeof SysX7k9ControlProductsRoute
  '/sys-x7k9-control/promotions': typeof SysX7k9ControlPromotionsRoute
  '/sys-x7k9-control/related-clicks': typeof SysX7k9ControlRelatedClicksRoute
  '/sys-x7k9-control/reviews': typeof SysX7k9ControlReviewsRoute
  '/sys-x7k9-control/settings': typeof SysX7k9ControlSettingsRoute
  '/sys-x7k9-control/shipping': typeof SysX7k9ControlShippingRoute
  '/sys-x7k9-control/site-customization': typeof SysX7k9ControlSiteCustomizationRoute
  '/sys-x7k9-control/staff': typeof SysX7k9ControlStaffRoute
  '/sys-x7k9-control/vendors': typeof SysX7k9ControlVendorsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/store': typeof VendorStoreRoute
  '/dropshipping/': typeof DropshippingIndexRoute
  '/sys-x7k9-control/': typeof SysX7k9ControlIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/redeploy': typeof ApiPublicRedeployRoute
  '/dropshipping/order-confirmation/$orderId': typeof DropshippingOrderConfirmationOrderIdRoute
  '/dropshipping/order/$importId': typeof DropshippingOrderImportIdRoute
  '/dropshipping/view/$importId': typeof DropshippingViewImportIdRoute
  '/sys-x7k9-control/orders/$id': typeof SysX7k9ControlOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dropshipping/apply': typeof DropshippingApplyRoute
  '/dropshipping/earnings': typeof DropshippingEarningsRoute
  '/dropshipping/links': typeof DropshippingLinksRoute
  '/dropshipping/marketing': typeof DropshippingMarketingRoute
  '/dropshipping/orders': typeof DropshippingOrdersRoute
  '/dropshipping/payouts': typeof DropshippingPayoutsRoute
  '/dropshipping/products': typeof DropshippingProductsRoute
  '/dropshipping/settings': typeof DropshippingSettingsRoute
  '/ds/$slug': typeof DsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/p/$slug': typeof PSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$slug': typeof StoreSlugRoute
  '/sys-x7k9-control/affiliates': typeof SysX7k9ControlAffiliatesRoute
  '/sys-x7k9-control/analytics': typeof SysX7k9ControlAnalyticsRoute
  '/sys-x7k9-control/audit-logs': typeof SysX7k9ControlAuditLogsRoute
  '/sys-x7k9-control/banners': typeof SysX7k9ControlBannersRoute
  '/sys-x7k9-control/categories': typeof SysX7k9ControlCategoriesRoute
  '/sys-x7k9-control/coupons': typeof SysX7k9ControlCouponsRoute
  '/sys-x7k9-control/customers': typeof SysX7k9ControlCustomersRoute
  '/sys-x7k9-control/dropshippers': typeof SysX7k9ControlDropshippersRoute
  '/sys-x7k9-control/dropshipping-announcements': typeof SysX7k9ControlDropshippingAnnouncementsRoute
  '/sys-x7k9-control/dropshipping-earnings': typeof SysX7k9ControlDropshippingEarningsRoute
  '/sys-x7k9-control/dropshipping-payouts': typeof SysX7k9ControlDropshippingPayoutsRoute
  '/sys-x7k9-control/dropshipping-settings': typeof SysX7k9ControlDropshippingSettingsRoute
  '/sys-x7k9-control/ds-diagnostic': typeof SysX7k9ControlDsDiagnosticRoute
  '/sys-x7k9-control/locations-check': typeof SysX7k9ControlLocationsCheckRoute
  '/sys-x7k9-control/offers': typeof SysX7k9ControlOffersRoute
  '/sys-x7k9-control/orders': typeof SysX7k9ControlOrdersRoute
  '/sys-x7k9-control/password-resets': typeof SysX7k9ControlPasswordResetsRoute
  '/sys-x7k9-control/products': typeof SysX7k9ControlProductsRoute
  '/sys-x7k9-control/promotions': typeof SysX7k9ControlPromotionsRoute
  '/sys-x7k9-control/related-clicks': typeof SysX7k9ControlRelatedClicksRoute
  '/sys-x7k9-control/reviews': typeof SysX7k9ControlReviewsRoute
  '/sys-x7k9-control/settings': typeof SysX7k9ControlSettingsRoute
  '/sys-x7k9-control/shipping': typeof SysX7k9ControlShippingRoute
  '/sys-x7k9-control/site-customization': typeof SysX7k9ControlSiteCustomizationRoute
  '/sys-x7k9-control/staff': typeof SysX7k9ControlStaffRoute
  '/sys-x7k9-control/vendors': typeof SysX7k9ControlVendorsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/store': typeof VendorStoreRoute
  '/dropshipping': typeof DropshippingIndexRoute
  '/sys-x7k9-control': typeof SysX7k9ControlIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/redeploy': typeof ApiPublicRedeployRoute
  '/dropshipping/order-confirmation/$orderId': typeof DropshippingOrderConfirmationOrderIdRoute
  '/dropshipping/order/$importId': typeof DropshippingOrderImportIdRoute
  '/dropshipping/view/$importId': typeof DropshippingViewImportIdRoute
  '/sys-x7k9-control/orders/$id': typeof SysX7k9ControlOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/dropshipping': typeof DropshippingRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sys-x7k9-control': typeof SysX7k9ControlRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dropshipping/apply': typeof DropshippingApplyRoute
  '/dropshipping/earnings': typeof DropshippingEarningsRoute
  '/dropshipping/links': typeof DropshippingLinksRoute
  '/dropshipping/marketing': typeof DropshippingMarketingRoute
  '/dropshipping/orders': typeof DropshippingOrdersRoute
  '/dropshipping/payouts': typeof DropshippingPayoutsRoute
  '/dropshipping/products': typeof DropshippingProductsRoute
  '/dropshipping/settings': typeof DropshippingSettingsRoute
  '/ds/$slug': typeof DsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/p/$slug': typeof PSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$slug': typeof StoreSlugRoute
  '/sys-x7k9-control/affiliates': typeof SysX7k9ControlAffiliatesRoute
  '/sys-x7k9-control/analytics': typeof SysX7k9ControlAnalyticsRoute
  '/sys-x7k9-control/audit-logs': typeof SysX7k9ControlAuditLogsRoute
  '/sys-x7k9-control/banners': typeof SysX7k9ControlBannersRoute
  '/sys-x7k9-control/categories': typeof SysX7k9ControlCategoriesRoute
  '/sys-x7k9-control/coupons': typeof SysX7k9ControlCouponsRoute
  '/sys-x7k9-control/customers': typeof SysX7k9ControlCustomersRoute
  '/sys-x7k9-control/dropshippers': typeof SysX7k9ControlDropshippersRoute
  '/sys-x7k9-control/dropshipping-announcements': typeof SysX7k9ControlDropshippingAnnouncementsRoute
  '/sys-x7k9-control/dropshipping-earnings': typeof SysX7k9ControlDropshippingEarningsRoute
  '/sys-x7k9-control/dropshipping-payouts': typeof SysX7k9ControlDropshippingPayoutsRoute
  '/sys-x7k9-control/dropshipping-settings': typeof SysX7k9ControlDropshippingSettingsRoute
  '/sys-x7k9-control/ds-diagnostic': typeof SysX7k9ControlDsDiagnosticRoute
  '/sys-x7k9-control/locations-check': typeof SysX7k9ControlLocationsCheckRoute
  '/sys-x7k9-control/offers': typeof SysX7k9ControlOffersRoute
  '/sys-x7k9-control/orders': typeof SysX7k9ControlOrdersRoute
  '/sys-x7k9-control/password-resets': typeof SysX7k9ControlPasswordResetsRoute
  '/sys-x7k9-control/products': typeof SysX7k9ControlProductsRoute
  '/sys-x7k9-control/promotions': typeof SysX7k9ControlPromotionsRoute
  '/sys-x7k9-control/related-clicks': typeof SysX7k9ControlRelatedClicksRoute
  '/sys-x7k9-control/reviews': typeof SysX7k9ControlReviewsRoute
  '/sys-x7k9-control/settings': typeof SysX7k9ControlSettingsRoute
  '/sys-x7k9-control/shipping': typeof SysX7k9ControlShippingRoute
  '/sys-x7k9-control/site-customization': typeof SysX7k9ControlSiteCustomizationRoute
  '/sys-x7k9-control/staff': typeof SysX7k9ControlStaffRoute
  '/sys-x7k9-control/vendors': typeof SysX7k9ControlVendorsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/store': typeof VendorStoreRoute
  '/dropshipping/': typeof DropshippingIndexRoute
  '/sys-x7k9-control/': typeof SysX7k9ControlIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/redeploy': typeof ApiPublicRedeployRoute
  '/dropshipping/order-confirmation/$orderId': typeof DropshippingOrderConfirmationOrderIdRoute
  '/dropshipping/order/$importId': typeof DropshippingOrderImportIdRoute
  '/dropshipping/view/$importId': typeof DropshippingViewImportIdRoute
  '/sys-x7k9-control/orders_/$id': typeof SysX7k9ControlOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/affiliate'
    | '/auth'
    | '/become-vendor'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/dropshipping'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/orders'
    | '/reset-password'
    | '/search'
    | '/sys-x7k9-control'
    | '/vendor'
    | '/wishlist'
    | '/account/addresses'
    | '/category/$slug'
    | '/dropshipping/apply'
    | '/dropshipping/earnings'
    | '/dropshipping/links'
    | '/dropshipping/marketing'
    | '/dropshipping/orders'
    | '/dropshipping/payouts'
    | '/dropshipping/products'
    | '/dropshipping/settings'
    | '/ds/$slug'
    | '/order/$id'
    | '/p/$slug'
    | '/product/$id'
    | '/store/$slug'
    | '/sys-x7k9-control/affiliates'
    | '/sys-x7k9-control/analytics'
    | '/sys-x7k9-control/audit-logs'
    | '/sys-x7k9-control/banners'
    | '/sys-x7k9-control/categories'
    | '/sys-x7k9-control/coupons'
    | '/sys-x7k9-control/customers'
    | '/sys-x7k9-control/dropshippers'
    | '/sys-x7k9-control/dropshipping-announcements'
    | '/sys-x7k9-control/dropshipping-earnings'
    | '/sys-x7k9-control/dropshipping-payouts'
    | '/sys-x7k9-control/dropshipping-settings'
    | '/sys-x7k9-control/ds-diagnostic'
    | '/sys-x7k9-control/locations-check'
    | '/sys-x7k9-control/offers'
    | '/sys-x7k9-control/orders'
    | '/sys-x7k9-control/password-resets'
    | '/sys-x7k9-control/products'
    | '/sys-x7k9-control/promotions'
    | '/sys-x7k9-control/related-clicks'
    | '/sys-x7k9-control/reviews'
    | '/sys-x7k9-control/settings'
    | '/sys-x7k9-control/shipping'
    | '/sys-x7k9-control/site-customization'
    | '/sys-x7k9-control/staff'
    | '/sys-x7k9-control/vendors'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/store'
    | '/dropshipping/'
    | '/sys-x7k9-control/'
    | '/vendor/'
    | '/api/public/bootstrap-admin'
    | '/api/public/redeploy'
    | '/dropshipping/order-confirmation/$orderId'
    | '/dropshipping/order/$importId'
    | '/dropshipping/view/$importId'
    | '/sys-x7k9-control/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/affiliate'
    | '/auth'
    | '/become-vendor'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/orders'
    | '/reset-password'
    | '/search'
    | '/wishlist'
    | '/account/addresses'
    | '/category/$slug'
    | '/dropshipping/apply'
    | '/dropshipping/earnings'
    | '/dropshipping/links'
    | '/dropshipping/marketing'
    | '/dropshipping/orders'
    | '/dropshipping/payouts'
    | '/dropshipping/products'
    | '/dropshipping/settings'
    | '/ds/$slug'
    | '/order/$id'
    | '/p/$slug'
    | '/product/$id'
    | '/store/$slug'
    | '/sys-x7k9-control/affiliates'
    | '/sys-x7k9-control/analytics'
    | '/sys-x7k9-control/audit-logs'
    | '/sys-x7k9-control/banners'
    | '/sys-x7k9-control/categories'
    | '/sys-x7k9-control/coupons'
    | '/sys-x7k9-control/customers'
    | '/sys-x7k9-control/dropshippers'
    | '/sys-x7k9-control/dropshipping-announcements'
    | '/sys-x7k9-control/dropshipping-earnings'
    | '/sys-x7k9-control/dropshipping-payouts'
    | '/sys-x7k9-control/dropshipping-settings'
    | '/sys-x7k9-control/ds-diagnostic'
    | '/sys-x7k9-control/locations-check'
    | '/sys-x7k9-control/offers'
    | '/sys-x7k9-control/orders'
    | '/sys-x7k9-control/password-resets'
    | '/sys-x7k9-control/products'
    | '/sys-x7k9-control/promotions'
    | '/sys-x7k9-control/related-clicks'
    | '/sys-x7k9-control/reviews'
    | '/sys-x7k9-control/settings'
    | '/sys-x7k9-control/shipping'
    | '/sys-x7k9-control/site-customization'
    | '/sys-x7k9-control/staff'
    | '/sys-x7k9-control/vendors'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/store'
    | '/dropshipping'
    | '/sys-x7k9-control'
    | '/vendor'
    | '/api/public/bootstrap-admin'
    | '/api/public/redeploy'
    | '/dropshipping/order-confirmation/$orderId'
    | '/dropshipping/order/$importId'
    | '/dropshipping/view/$importId'
    | '/sys-x7k9-control/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/affiliate'
    | '/auth'
    | '/become-vendor'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/dropshipping'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/orders'
    | '/reset-password'
    | '/search'
    | '/sys-x7k9-control'
    | '/vendor'
    | '/wishlist'
    | '/account/addresses'
    | '/category/$slug'
    | '/dropshipping/apply'
    | '/dropshipping/earnings'
    | '/dropshipping/links'
    | '/dropshipping/marketing'
    | '/dropshipping/orders'
    | '/dropshipping/payouts'
    | '/dropshipping/products'
    | '/dropshipping/settings'
    | '/ds/$slug'
    | '/order/$id'
    | '/p/$slug'
    | '/product/$id'
    | '/store/$slug'
    | '/sys-x7k9-control/affiliates'
    | '/sys-x7k9-control/analytics'
    | '/sys-x7k9-control/audit-logs'
    | '/sys-x7k9-control/banners'
    | '/sys-x7k9-control/categories'
    | '/sys-x7k9-control/coupons'
    | '/sys-x7k9-control/customers'
    | '/sys-x7k9-control/dropshippers'
    | '/sys-x7k9-control/dropshipping-announcements'
    | '/sys-x7k9-control/dropshipping-earnings'
    | '/sys-x7k9-control/dropshipping-payouts'
    | '/sys-x7k9-control/dropshipping-settings'
    | '/sys-x7k9-control/ds-diagnostic'
    | '/sys-x7k9-control/locations-check'
    | '/sys-x7k9-control/offers'
    | '/sys-x7k9-control/orders'
    | '/sys-x7k9-control/password-resets'
    | '/sys-x7k9-control/products'
    | '/sys-x7k9-control/promotions'
    | '/sys-x7k9-control/related-clicks'
    | '/sys-x7k9-control/reviews'
    | '/sys-x7k9-control/settings'
    | '/sys-x7k9-control/shipping'
    | '/sys-x7k9-control/site-customization'
    | '/sys-x7k9-control/staff'
    | '/sys-x7k9-control/vendors'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/store'
    | '/dropshipping/'
    | '/sys-x7k9-control/'
    | '/vendor/'
    | '/api/public/bootstrap-admin'
    | '/api/public/redeploy'
    | '/dropshipping/order-confirmation/$orderId'
    | '/dropshipping/order/$importId'
    | '/dropshipping/view/$importId'
    | '/sys-x7k9-control/orders_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AffiliateRoute: typeof AffiliateRoute
  AuthRoute: typeof AuthRoute
  BecomeVendorRoute: typeof BecomeVendorRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  DropshippingRoute: typeof DropshippingRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OrdersRoute: typeof OrdersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SysX7k9ControlRoute: typeof SysX7k9ControlRouteWithChildren
  VendorRoute: typeof VendorRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DsSlugRoute: typeof DsSlugRoute
  OrderIdRoute: typeof OrderIdRoute
  PSlugRoute: typeof PSlugRoute
  ProductIdRoute: typeof ProductIdRoute
  StoreSlugRoute: typeof StoreSlugRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicRedeployRoute: typeof ApiPublicRedeployRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sys-x7k9-control': {
      id: '/sys-x7k9-control'
      path: '/sys-x7k9-control'
      fullPath: '/sys-x7k9-control'
      preLoaderRoute: typeof SysX7k9ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropshipping': {
      id: '/dropshipping'
      path: '/dropshipping'
      fullPath: '/dropshipping'
      preLoaderRoute: typeof DropshippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-vendor': {
      id: '/become-vendor'
      path: '/become-vendor'
      fullPath: '/become-vendor'
      preLoaderRoute: typeof BecomeVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/sys-x7k9-control/': {
      id: '/sys-x7k9-control/'
      path: '/'
      fullPath: '/sys-x7k9-control/'
      preLoaderRoute: typeof SysX7k9ControlIndexRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/dropshipping/': {
      id: '/dropshipping/'
      path: '/'
      fullPath: '/dropshipping/'
      preLoaderRoute: typeof DropshippingIndexRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/vendor/store': {
      id: '/vendor/store'
      path: '/store'
      fullPath: '/vendor/store'
      preLoaderRoute: typeof VendorStoreRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/sys-x7k9-control/vendors': {
      id: '/sys-x7k9-control/vendors'
      path: '/vendors'
      fullPath: '/sys-x7k9-control/vendors'
      preLoaderRoute: typeof SysX7k9ControlVendorsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/staff': {
      id: '/sys-x7k9-control/staff'
      path: '/staff'
      fullPath: '/sys-x7k9-control/staff'
      preLoaderRoute: typeof SysX7k9ControlStaffRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/site-customization': {
      id: '/sys-x7k9-control/site-customization'
      path: '/site-customization'
      fullPath: '/sys-x7k9-control/site-customization'
      preLoaderRoute: typeof SysX7k9ControlSiteCustomizationRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/shipping': {
      id: '/sys-x7k9-control/shipping'
      path: '/shipping'
      fullPath: '/sys-x7k9-control/shipping'
      preLoaderRoute: typeof SysX7k9ControlShippingRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/settings': {
      id: '/sys-x7k9-control/settings'
      path: '/settings'
      fullPath: '/sys-x7k9-control/settings'
      preLoaderRoute: typeof SysX7k9ControlSettingsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/reviews': {
      id: '/sys-x7k9-control/reviews'
      path: '/reviews'
      fullPath: '/sys-x7k9-control/reviews'
      preLoaderRoute: typeof SysX7k9ControlReviewsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/related-clicks': {
      id: '/sys-x7k9-control/related-clicks'
      path: '/related-clicks'
      fullPath: '/sys-x7k9-control/related-clicks'
      preLoaderRoute: typeof SysX7k9ControlRelatedClicksRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/promotions': {
      id: '/sys-x7k9-control/promotions'
      path: '/promotions'
      fullPath: '/sys-x7k9-control/promotions'
      preLoaderRoute: typeof SysX7k9ControlPromotionsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/products': {
      id: '/sys-x7k9-control/products'
      path: '/products'
      fullPath: '/sys-x7k9-control/products'
      preLoaderRoute: typeof SysX7k9ControlProductsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/password-resets': {
      id: '/sys-x7k9-control/password-resets'
      path: '/password-resets'
      fullPath: '/sys-x7k9-control/password-resets'
      preLoaderRoute: typeof SysX7k9ControlPasswordResetsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/orders': {
      id: '/sys-x7k9-control/orders'
      path: '/orders'
      fullPath: '/sys-x7k9-control/orders'
      preLoaderRoute: typeof SysX7k9ControlOrdersRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/offers': {
      id: '/sys-x7k9-control/offers'
      path: '/offers'
      fullPath: '/sys-x7k9-control/offers'
      preLoaderRoute: typeof SysX7k9ControlOffersRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/locations-check': {
      id: '/sys-x7k9-control/locations-check'
      path: '/locations-check'
      fullPath: '/sys-x7k9-control/locations-check'
      preLoaderRoute: typeof SysX7k9ControlLocationsCheckRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/ds-diagnostic': {
      id: '/sys-x7k9-control/ds-diagnostic'
      path: '/ds-diagnostic'
      fullPath: '/sys-x7k9-control/ds-diagnostic'
      preLoaderRoute: typeof SysX7k9ControlDsDiagnosticRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/dropshipping-settings': {
      id: '/sys-x7k9-control/dropshipping-settings'
      path: '/dropshipping-settings'
      fullPath: '/sys-x7k9-control/dropshipping-settings'
      preLoaderRoute: typeof SysX7k9ControlDropshippingSettingsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/dropshipping-payouts': {
      id: '/sys-x7k9-control/dropshipping-payouts'
      path: '/dropshipping-payouts'
      fullPath: '/sys-x7k9-control/dropshipping-payouts'
      preLoaderRoute: typeof SysX7k9ControlDropshippingPayoutsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/dropshipping-earnings': {
      id: '/sys-x7k9-control/dropshipping-earnings'
      path: '/dropshipping-earnings'
      fullPath: '/sys-x7k9-control/dropshipping-earnings'
      preLoaderRoute: typeof SysX7k9ControlDropshippingEarningsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/dropshipping-announcements': {
      id: '/sys-x7k9-control/dropshipping-announcements'
      path: '/dropshipping-announcements'
      fullPath: '/sys-x7k9-control/dropshipping-announcements'
      preLoaderRoute: typeof SysX7k9ControlDropshippingAnnouncementsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/dropshippers': {
      id: '/sys-x7k9-control/dropshippers'
      path: '/dropshippers'
      fullPath: '/sys-x7k9-control/dropshippers'
      preLoaderRoute: typeof SysX7k9ControlDropshippersRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/customers': {
      id: '/sys-x7k9-control/customers'
      path: '/customers'
      fullPath: '/sys-x7k9-control/customers'
      preLoaderRoute: typeof SysX7k9ControlCustomersRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/coupons': {
      id: '/sys-x7k9-control/coupons'
      path: '/coupons'
      fullPath: '/sys-x7k9-control/coupons'
      preLoaderRoute: typeof SysX7k9ControlCouponsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/categories': {
      id: '/sys-x7k9-control/categories'
      path: '/categories'
      fullPath: '/sys-x7k9-control/categories'
      preLoaderRoute: typeof SysX7k9ControlCategoriesRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/banners': {
      id: '/sys-x7k9-control/banners'
      path: '/banners'
      fullPath: '/sys-x7k9-control/banners'
      preLoaderRoute: typeof SysX7k9ControlBannersRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/audit-logs': {
      id: '/sys-x7k9-control/audit-logs'
      path: '/audit-logs'
      fullPath: '/sys-x7k9-control/audit-logs'
      preLoaderRoute: typeof SysX7k9ControlAuditLogsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/analytics': {
      id: '/sys-x7k9-control/analytics'
      path: '/analytics'
      fullPath: '/sys-x7k9-control/analytics'
      preLoaderRoute: typeof SysX7k9ControlAnalyticsRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/sys-x7k9-control/affiliates': {
      id: '/sys-x7k9-control/affiliates'
      path: '/affiliates'
      fullPath: '/sys-x7k9-control/affiliates'
      preLoaderRoute: typeof SysX7k9ControlAffiliatesRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/$slug': {
      id: '/ds/$slug'
      path: '/ds/$slug'
      fullPath: '/ds/$slug'
      preLoaderRoute: typeof DsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropshipping/settings': {
      id: '/dropshipping/settings'
      path: '/settings'
      fullPath: '/dropshipping/settings'
      preLoaderRoute: typeof DropshippingSettingsRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/dropshipping/products': {
      id: '/dropshipping/products'
      path: '/products'
      fullPath: '/dropshipping/products'
      preLoaderRoute: typeof DropshippingProductsRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/dropshipping/payouts': {
      id: '/dropshipping/payouts'
      path: '/payouts'
      fullPath: '/dropshipping/payouts'
      preLoaderRoute: typeof DropshippingPayoutsRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/dropshipping/orders': {
      id: '/dropshipping/orders'
      path: '/orders'
      fullPath: '/dropshipping/orders'
      preLoaderRoute: typeof DropshippingOrdersRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/dropshipping/marketing': {
      id: '/dropshipping/marketing'
      path: '/marketing'
      fullPath: '/dropshipping/marketing'
      preLoaderRoute: typeof DropshippingMarketingRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/dropshipping/links': {
      id: '/dropshipping/links'
      path: '/links'
      fullPath: '/dropshipping/links'
      preLoaderRoute: typeof DropshippingLinksRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/dropshipping/earnings': {
      id: '/dropshipping/earnings'
      path: '/earnings'
      fullPath: '/dropshipping/earnings'
      preLoaderRoute: typeof DropshippingEarningsRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/dropshipping/apply': {
      id: '/dropshipping/apply'
      path: '/apply'
      fullPath: '/dropshipping/apply'
      preLoaderRoute: typeof DropshippingApplyRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/sys-x7k9-control/orders_/$id': {
      id: '/sys-x7k9-control/orders_/$id'
      path: '/orders/$id'
      fullPath: '/sys-x7k9-control/orders/$id'
      preLoaderRoute: typeof SysX7k9ControlOrdersIdRouteImport
      parentRoute: typeof SysX7k9ControlRoute
    }
    '/dropshipping/view/$importId': {
      id: '/dropshipping/view/$importId'
      path: '/view/$importId'
      fullPath: '/dropshipping/view/$importId'
      preLoaderRoute: typeof DropshippingViewImportIdRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/dropshipping/order/$importId': {
      id: '/dropshipping/order/$importId'
      path: '/order/$importId'
      fullPath: '/dropshipping/order/$importId'
      preLoaderRoute: typeof DropshippingOrderImportIdRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/dropshipping/order-confirmation/$orderId': {
      id: '/dropshipping/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/dropshipping/order-confirmation/$orderId'
      preLoaderRoute: typeof DropshippingOrderConfirmationOrderIdRouteImport
      parentRoute: typeof DropshippingRoute
    }
    '/api/public/redeploy': {
      id: '/api/public/redeploy'
      path: '/api/public/redeploy'
      fullPath: '/api/public/redeploy'
      preLoaderRoute: typeof ApiPublicRedeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface DropshippingRouteChildren {
  DropshippingApplyRoute: typeof DropshippingApplyRoute
  DropshippingEarningsRoute: typeof DropshippingEarningsRoute
  DropshippingLinksRoute: typeof DropshippingLinksRoute
  DropshippingMarketingRoute: typeof DropshippingMarketingRoute
  DropshippingOrdersRoute: typeof DropshippingOrdersRoute
  DropshippingPayoutsRoute: typeof DropshippingPayoutsRoute
  DropshippingProductsRoute: typeof DropshippingProductsRoute
  DropshippingSettingsRoute: typeof DropshippingSettingsRoute
  DropshippingIndexRoute: typeof DropshippingIndexRoute
  DropshippingOrderConfirmationOrderIdRoute: typeof DropshippingOrderConfirmationOrderIdRoute
  DropshippingOrderImportIdRoute: typeof DropshippingOrderImportIdRoute
  DropshippingViewImportIdRoute: typeof DropshippingViewImportIdRoute
}

const DropshippingRouteChildren: DropshippingRouteChildren = {
  DropshippingApplyRoute: DropshippingApplyRoute,
  DropshippingEarningsRoute: DropshippingEarningsRoute,
  DropshippingLinksRoute: DropshippingLinksRoute,
  DropshippingMarketingRoute: DropshippingMarketingRoute,
  DropshippingOrdersRoute: DropshippingOrdersRoute,
  DropshippingPayoutsRoute: DropshippingPayoutsRoute,
  DropshippingProductsRoute: DropshippingProductsRoute,
  DropshippingSettingsRoute: DropshippingSettingsRoute,
  DropshippingIndexRoute: DropshippingIndexRoute,
  DropshippingOrderConfirmationOrderIdRoute:
    DropshippingOrderConfirmationOrderIdRoute,
  DropshippingOrderImportIdRoute: DropshippingOrderImportIdRoute,
  DropshippingViewImportIdRoute: DropshippingViewImportIdRoute,
}

const DropshippingRouteWithChildren = DropshippingRoute._addFileChildren(
  DropshippingRouteChildren,
)

interface SysX7k9ControlRouteChildren {
  SysX7k9ControlAffiliatesRoute: typeof SysX7k9ControlAffiliatesRoute
  SysX7k9ControlAnalyticsRoute: typeof SysX7k9ControlAnalyticsRoute
  SysX7k9ControlAuditLogsRoute: typeof SysX7k9ControlAuditLogsRoute
  SysX7k9ControlBannersRoute: typeof SysX7k9ControlBannersRoute
  SysX7k9ControlCategoriesRoute: typeof SysX7k9ControlCategoriesRoute
  SysX7k9ControlCouponsRoute: typeof SysX7k9ControlCouponsRoute
  SysX7k9ControlCustomersRoute: typeof SysX7k9ControlCustomersRoute
  SysX7k9ControlDropshippersRoute: typeof SysX7k9ControlDropshippersRoute
  SysX7k9ControlDropshippingAnnouncementsRoute: typeof SysX7k9ControlDropshippingAnnouncementsRoute
  SysX7k9ControlDropshippingEarningsRoute: typeof SysX7k9ControlDropshippingEarningsRoute
  SysX7k9ControlDropshippingPayoutsRoute: typeof SysX7k9ControlDropshippingPayoutsRoute
  SysX7k9ControlDropshippingSettingsRoute: typeof SysX7k9ControlDropshippingSettingsRoute
  SysX7k9ControlDsDiagnosticRoute: typeof SysX7k9ControlDsDiagnosticRoute
  SysX7k9ControlLocationsCheckRoute: typeof SysX7k9ControlLocationsCheckRoute
  SysX7k9ControlOffersRoute: typeof SysX7k9ControlOffersRoute
  SysX7k9ControlOrdersRoute: typeof SysX7k9ControlOrdersRoute
  SysX7k9ControlPasswordResetsRoute: typeof SysX7k9ControlPasswordResetsRoute
  SysX7k9ControlProductsRoute: typeof SysX7k9ControlProductsRoute
  SysX7k9ControlPromotionsRoute: typeof SysX7k9ControlPromotionsRoute
  SysX7k9ControlRelatedClicksRoute: typeof SysX7k9ControlRelatedClicksRoute
  SysX7k9ControlReviewsRoute: typeof SysX7k9ControlReviewsRoute
  SysX7k9ControlSettingsRoute: typeof SysX7k9ControlSettingsRoute
  SysX7k9ControlShippingRoute: typeof SysX7k9ControlShippingRoute
  SysX7k9ControlSiteCustomizationRoute: typeof SysX7k9ControlSiteCustomizationRoute
  SysX7k9ControlStaffRoute: typeof SysX7k9ControlStaffRoute
  SysX7k9ControlVendorsRoute: typeof SysX7k9ControlVendorsRoute
  SysX7k9ControlIndexRoute: typeof SysX7k9ControlIndexRoute
  SysX7k9ControlOrdersIdRoute: typeof SysX7k9ControlOrdersIdRoute
}

const SysX7k9ControlRouteChildren: SysX7k9ControlRouteChildren = {
  SysX7k9ControlAffiliatesRoute: SysX7k9ControlAffiliatesRoute,
  SysX7k9ControlAnalyticsRoute: SysX7k9ControlAnalyticsRoute,
  SysX7k9ControlAuditLogsRoute: SysX7k9ControlAuditLogsRoute,
  SysX7k9ControlBannersRoute: SysX7k9ControlBannersRoute,
  SysX7k9ControlCategoriesRoute: SysX7k9ControlCategoriesRoute,
  SysX7k9ControlCouponsRoute: SysX7k9ControlCouponsRoute,
  SysX7k9ControlCustomersRoute: SysX7k9ControlCustomersRoute,
  SysX7k9ControlDropshippersRoute: SysX7k9ControlDropshippersRoute,
  SysX7k9ControlDropshippingAnnouncementsRoute:
    SysX7k9ControlDropshippingAnnouncementsRoute,
  SysX7k9ControlDropshippingEarningsRoute:
    SysX7k9ControlDropshippingEarningsRoute,
  SysX7k9ControlDropshippingPayoutsRoute:
    SysX7k9ControlDropshippingPayoutsRoute,
  SysX7k9ControlDropshippingSettingsRoute:
    SysX7k9ControlDropshippingSettingsRoute,
  SysX7k9ControlDsDiagnosticRoute: SysX7k9ControlDsDiagnosticRoute,
  SysX7k9ControlLocationsCheckRoute: SysX7k9ControlLocationsCheckRoute,
  SysX7k9ControlOffersRoute: SysX7k9ControlOffersRoute,
  SysX7k9ControlOrdersRoute: SysX7k9ControlOrdersRoute,
  SysX7k9ControlPasswordResetsRoute: SysX7k9ControlPasswordResetsRoute,
  SysX7k9ControlProductsRoute: SysX7k9ControlProductsRoute,
  SysX7k9ControlPromotionsRoute: SysX7k9ControlPromotionsRoute,
  SysX7k9ControlRelatedClicksRoute: SysX7k9ControlRelatedClicksRoute,
  SysX7k9ControlReviewsRoute: SysX7k9ControlReviewsRoute,
  SysX7k9ControlSettingsRoute: SysX7k9ControlSettingsRoute,
  SysX7k9ControlShippingRoute: SysX7k9ControlShippingRoute,
  SysX7k9ControlSiteCustomizationRoute: SysX7k9ControlSiteCustomizationRoute,
  SysX7k9ControlStaffRoute: SysX7k9ControlStaffRoute,
  SysX7k9ControlVendorsRoute: SysX7k9ControlVendorsRoute,
  SysX7k9ControlIndexRoute: SysX7k9ControlIndexRoute,
  SysX7k9ControlOrdersIdRoute: SysX7k9ControlOrdersIdRoute,
}

const SysX7k9ControlRouteWithChildren = SysX7k9ControlRoute._addFileChildren(
  SysX7k9ControlRouteChildren,
)

interface VendorRouteChildren {
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorProductsRoute: typeof VendorProductsRoute
  VendorStoreRoute: typeof VendorStoreRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorOrdersRoute: VendorOrdersRoute,
  VendorProductsRoute: VendorProductsRoute,
  VendorStoreRoute: VendorStoreRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AffiliateRoute: AffiliateRoute,
  AuthRoute: AuthRoute,
  BecomeVendorRoute: BecomeVendorRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  DropshippingRoute: DropshippingRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OrdersRoute: OrdersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SysX7k9ControlRoute: SysX7k9ControlRouteWithChildren,
  VendorRoute: VendorRouteWithChildren,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  DsSlugRoute: DsSlugRoute,
  OrderIdRoute: OrderIdRoute,
  PSlugRoute: PSlugRoute,
  ProductIdRoute: ProductIdRoute,
  StoreSlugRoute: StoreSlugRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicRedeployRoute: ApiPublicRedeployRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
